### ISSUE TITLE
`jblas` causes UnsatisfiedLinkError on aarch64 (m1) mac

### ISSUE THREAD

**Issue by sirno** [CompEvol/beast2#1047]
On BEAST v2.6.7 the following issue arises with the MultiTypeTree Package on a fully updated M1 Mac.

I suppose the best shot at fixing this would be upgrading to version 2.7.0, but the packages are not yet available there.

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at beast.app.beastapp.BeastLauncher.run(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: 'void org.jblas.NativeBlas.dgemm(char, char, int, int, int, double, double[], int, int, double[], int, int, double, double[], int, int)'
	at org.jblas.NativeBlas.dgemm(Native Method)
	at org.jblas.SimpleBlas.gemm(SimpleBlas.java:247)
	at org.jblas.DoubleMatrix.mmuli(DoubleMatrix.java:1781)
	at org.jblas.DoubleMatrix.mmul(DoubleMatrix.java:3138)
	at org.jblas.MatrixFunctions.expm(MatrixFunctions.java:428)
	at multitypetree.operators.UniformizationRetypeOperator.getBranchTypeProb(Unknown Source)
	at multitypetree.operators.NodeShiftRetype.nonRootProposal(Unknown Source)
	at multitypetree.operators.NodeShiftRetype.proposal(Unknown Source)
	at beast.core.Operator.proposal(Unknown Source)
	at beast.core.MCMC.propagateState(Unknown Source)
	at beast.core.MCMC.doLoop(Unknown Source)
	at beast.core.MCMC.run(Unknown Source)
	at beast.app.BeastMCMC.run(Unknown Source)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 3 more
-- org.jblas INFO Deleting /var/folders/sl/b99vml7s45q3zx3wb1fqvq240000gp/T/jblas15640803248391520753
```

**Comment by rbouckaert** [comment]
@tgvaughan just to clarify, jblas is bundled with a number of packages (like MultiTypeTree and Mascot) but not with BEAST.base. Shouldn't this issue be opened for the corresponding packages?

**Comment by sirno** [comment]
I think it makes sense to track it here, so people can find the issue when the encounter it in any package. aarch64 systems get more and more common. also a new version shouldn't be too far away. there are already working build scripts in the jblas prs.

**Comment by tochsner** [comment]
I got it to work by cloning the fork from [this jblas PR](https://github.com/jblas-project/jblas/pull/135). Then I rebuilt jblas locally on my M2 macbook using `mvn clean install` and used the generated `.jar` file.
