### ISSUE TITLE
command line packagemanager issue with fresh install

### ISSUE THREAD

**Issue by ntakebay** [CompEvol/beast2#1071]
I installed beast 2.7.1 on linux, and immediately tried to update to 2.7.2 with packagemanager -useAppDir -updatenow

It fails with the message:

Install failed because /root/.beast/2.7/toDeleteList (No such file or directory)
java.io.FileNotFoundException: /root/.beast/2.7/toDeleteList (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at java.base/java.io.FileWriter.<init>(Unknown Source)
	at beast.pkgmgmt.PackageManager.uninstallPackage(Unknown Source)
	at beast.pkgmgmt.PackageManager.uninstallPackage(Unknown Source)
	at beast.pkgmgmt.PackageManager.prepareForInstall(Unknown Source)
	at beast.pkgmgmt.PackageManager.updatePackages(Unknown Source)
	at beast.pkgmgmt.PackageManager.main(Unknown Source)

This is coming from the directory /root/.beast/2.7 doesn't exists.  After making the directory with mkdir -p /root/.beast/2.7 (or runs GUI beauti at first), the problem goes away.  But you might want to let packagemanager to check and create the directory if it doesn't exists.

**Comment by bmichanderson** [comment]
Note that this still doesn't work unless the directory is manually created. (trying to install in a Singularity container with Ubuntu 22.04)

Later commands with `-useAppDir` indicate that the `Packages user path : /root/.beast/2.7` but then when installing packages they say, e.g. `Package BICEPS is installed in /usr/local/share/beast/2.7/BICEPS`, so the user path message is confusing.

Attempting to use the `-updatenow` command results in a message that `Upgrading packages on your machine requires BEAUti to restart` when there is no GUI being used. Is that intended and OK for command line installation?

Installing packages results in updates to the BEAST.base and BEAST.app packages without explicitly running an update command.

Here are my commands:
```
# add directory to avoid error
mkdir -p /root/.beast/2.7

# update
/beast/bin/packagemanager -useAppDir -updatenow

# install packages for species delimitation
/beast/bin/packagemanager -useAppDir -add SNAPP
/beast/bin/packagemanager -useAppDir -add snapper
/beast/bin/packagemanager -useAppDir -add MODEL_SELECTION
/beast/bin/packagemanager -useAppDir -add starbeast3
/beast/bin/packagemanager -useAppDir -add BICEPS
/beast/bin/packagemanager -useAppDir -add speedemon
```

And the first two outputs:
```
+ mkdir -p /root/.beast/2.7
+ /beast/bin/packagemanager -useAppDir -updatenow
Upgrading packages on your machine requires BEAUti to restart.
+ /beast/bin/packagemanager -useAppDir -add SNAPP
Packages user path : /root/.beast/2.7
Access URL : https://raw.githubusercontent.com/CompEvol/CBAN/master/packages2.7.xml
Getting list of packages ...Done!

Determine packages to install
Start installation
Package SNAPP is installed in /usr/local/share/beast/2.7/SNAPP.
Package BEAST.base is installed in /usr/local/share/beast/2.7/BEAST.base.
Package BEAST.app is installed in /usr/local/share/beast/2.7/BEAST.app.
Package BEASTLabs is installed in /usr/local/share/beast/2.7/BEASTLabs.
+ /beast/bin/packagemanager -useAppDir -add snapper
Packages user path : /root/.beast/2.7
Access URL : https://raw.githubusercontent.com/CompEvol/CBAN/master/packages2.7.xml
Getting list of packages ...Done!
```

**Comment by rbouckaert** [comment]
Perhaps the easiest way to create the package directory is to run `/beast/bin/beast -version` before installing packages. This means there is no need to remember the exact location of the package directory, which can change with different versions and operating systems.

**Comment by bmichanderson** [comment]
Thanks Remco, that does avoid the error that it can't find the directory, and now it says the packages are installed in the BEAST `/root/.beast/2.7` directory.
The `-updatenow` command now also installs additional packages, so my later command to add starbeast3 leads to a failure:
```
Installation aborted: starbeast3 is already installed.
```

If I comment out my command to install starbeast3, the process completes, but now some weird things happen. The individual package installations all get put in `/usr/local/share/beast/2.7/`, and if I run this afterward with the created container:
```
singularity exec -H "$(pwd)" snapper.sif packagemanager -list
```
it says that BEAST.base is still 2.7.7, that BEAST.app is "NA", and that starbeast3 is "NA". 
During installation (checking with `/beast/bin/beast -version`) they were all installed and the BEAST packages were 2.7.8.

I shelled into the container and found there was no `/root/.beast` directory, instead the packages had been installed in `/usr/local/share/beast/2.7`, and starbeast3 was absent. When I ran `beast -version`, it complained that BEASTLabs (and other necessary packages) weren't installed even though they had been during the `-updatenow` command in container creation.

So it seems during container creation the installation sees a root directory and does things there, but the `-useAppDir` is putting things somewhere else. The command `packagemanager -useAppDir -updatenow` doesn't seem to update packages in the app directory. It seems that I don't know what I should be doing to install BEAST in the container, but my previous implementation (manually creating the folder) is at least updating packages. If I run `beast -version` in that container, it has both versions of BEAST packages (2.7.7 and 2.7.8) and all the other packages.

**Comment by bmichanderson** [comment]
If I build the container this way:
```
# check version (and auto-create expected files to avoid errors)
/beast/bin/beast -version

# install packages for species delimitation
/beast/bin/packagemanager -useAppDir -add SNAPP
/beast/bin/packagemanager -useAppDir -add snapper
/beast/bin/packagemanager -useAppDir -add MODEL_SELECTION
/beast/bin/packagemanager -useAppDir -add starbeast3
/beast/bin/packagemanager -useAppDir -add BICEPS
/beast/bin/packagemanager -useAppDir -add speedemon

# try to update to 2.7.8
/beast/bin/packagemanager -updatenow
```
The output of `singularity exec -H "$(pwd)" snapper.sif beast -version`
```
BEAST v2.7.7
---
BEAST.app v2.7.7
BEAST.base v2.7.7
BEASTLabs v2.0.3
BICEPS v1.1.2
MODEL_SELECTION v1.6.2
ORC v1.2.1
SA v2.1.1
SNAPP v1.6.1
snapper v1.1.5
speedemon v1.1.0
starbeast3 v1.2.1
---
Java version 17.0.3
```

If I build the container this way:
```
# add directory to avoid issues
mkdir -p ~/.beast/2.7

# install packages for species delimitation
/beast/bin/packagemanager -useAppDir -add SNAPP
/beast/bin/packagemanager -useAppDir -add snapper
/beast/bin/packagemanager -useAppDir -add MODEL_SELECTION
/beast/bin/packagemanager -useAppDir -add starbeast3
/beast/bin/packagemanager -useAppDir -add BICEPS
/beast/bin/packagemanager -useAppDir -add speedemon

# no update command
```
The output of `singularity exec -H "$(pwd)" snapper.sif beast -version`:
```
BEAST v2.7.7
---
BEAST.app v2.7.7
BEAST.base v2.7.7
BEAST.app v2.7.8
BEAST.base v2.7.8
BEASTLabs v2.0.3
BICEPS v1.1.2
MODEL_SELECTION v1.6.2
ORC v1.2.1
SA v2.1.1
SNAPP v1.6.1
snapper v1.1.5
speedemon v1.1.0
starbeast3 v1.2.1
---
Java version 17.0.3
```

I assume that means it will be using 2.7.8, but maybe I'm wrong about that.

**Comment by rbouckaert** [comment]
The first line `BEAST v2.7.7` shows you use v2.7.7 for the package manager, which then loads al other packaged.

However, having both `BEAST.app v2.7.7` and `BEAST.app v2.7.8` suggests something went wrong: either one or the other is loaded, and it is not clear which one (the first one loaded blocks the other one, and the order of packages suggest this is probably v2.7.7, not 2.7.8).

To fix this, remove the package directory `BEAST.app` and `BEAST.base` -- make sure it is the one containing v2.7.7 by checking the first line of the file `BEAST.base/version.xml`, which should show `<package name='BEAST.base' version='2.7.8'>`.

**Comment by bmichanderson** [comment]
OK, so the behaviour with the container seems to be problematic. I added the command to remove the `/root/.beast/` directory during container creation and it is gone, but the `beast -version` command still shows both 2.7.7 and 2.7.8.

If I run `packagemanager -list`, only 2.7.8 is visible, and I think I can see what's happening. When the `packagemanager` app is called in the container, it just looks at the `/usr/local/share/beast/2.7` folder in the container where the install happened. When `beast` is called in the container, it defaults to creating a `.beast` folder in the host's home directory, where it puts the 2.7.7 BEAST.app and BEAST.base packages, regardless of what has been installed in the container (2.7.8). I noticed this behaviour before (creating the `.beast` folder on run), which is why I bind the working directory to home so I can run it on the supercomputer without it creating/checking the home directory there (my intention for using a container is to keep the analysis isolated and reproducible without affecting the host environment).

Since the 2.7.8 was not a full release on GitHub, I don't seem to have a way of installing it independently of installing 2.7.7, and if that is the default for the executable that is downloaded, I don't know how to use the updated 2.7.8 app.

**Comment by rbouckaert** [comment]
Would something like this work for your container:
```
apt-get update
apt-get install wget
wget https://github.com/CompEvol/beast2/releases/download/v2.7.7/BEAST.v2.7.7.Linux.x86.tgz
tar fxz BEAST.v2.7.7.Linux.x86.tgz 
beast/bin/beast -version
beast/bin/packagemanager -updatenow
beast/bin/beast -version
```
In a container, this shows
```
BEAST v2.7.7
---
BEAST.base v2.7.8
BEAST.app v2.7.8
ORC v1.2.1
SA v2.1.1
starbeast3 v1.2.1
BEASTLabs v2.0.3
CCD v1.0.3
```
so no duplicates of BEAST.app any more. Packages will be in `/root/.beast/2.7/`, so not quite sure whether that suits you.

**Comment by bmichanderson** [comment]
For me this doesn't work. After creation of the container, the '/root' directory doesn't appear to be there, and calling `beast -version` only shows the 2.7.7 and no added packages. The only way I have found to add packages is to use `-useAppDir`, which as detailed above adds the 2.7.8 but alongside the 2.7.7 that beast automatically creates in the home directory.
Every time the container is called to use `beast`, it creates a directory `.beast` in whatever is bound to home `~` if there isn't one there already.
Maybe beast could be changed to not do this if a `/usr/local/share/beast` folder already exists? Or allow the `-useAppDir` to be used to install and update beast itself? These don't seem like easy fixes, so perhaps I just have to wait until the next version is released as a full install. Or maybe my Singularity skills are not up to implementing this properly.
