### ISSUE TITLE
java.lang.IllegalArgumentException: n must be positive

### ISSUE THREAD

**Issue by sevmurdock** [CompEvol/beast2#1080]
Having the Java error bellow when trying to Run Beast2 
Using Nexus File produced by converting a VCF file to a genlight in R and then converting the genlight to Nexus with the package DART

gl <- gl.compliance.check(gl)
gl2snapp(gl,outpath=getwd(),verbose=3)

Following the tutorial from Josh Banta  

https://www.youtube.com/watch?v=1qA4N4t6hLs&t=693s

java.lang.IllegalArgumentException: n must be positive
	at beast.base.util.MersenneTwisterFast.nextInt(Unknown Source)
	at beast.base.util.Randomizer.nextInt(Unknown Source)
	at snap.operators.NodeBudger.proposal(Unknown Source)
	at beast.base.inference.Operator.proposal(Unknown Source)
	at beast.base.inference.MCMC.propagateState(Unknown Source)
	at beast.base.inference.MCMC.doLoop(Unknown Source)
	at beast.base.inference.MCMC.run(Unknown Source)
	at beastfx.app.beast.BeastMCMC.run(Unknown Source)
	at beastfx.app.beast.Controller$2.run(Unknown Source)

**Comment by sevmurdock** [comment]
[snap.log](https://github.com/CompEvol/beast2/files/10553619/snap.log)

**Comment by zyy-1111** [comment]
I met the same problem, could you tell me your solution? Thanks a lot.

**Comment by zyy-1111** [comment]
![image](https://github.com/CompEvol/beast2/assets/81152546/9057db8c-6ef5-4364-8fdc-c4f075c6993d)
