### ISSUE TITLE
Error Parsing Input Tree: Around line 6744 which is the end of the .trees file

### ISSUE THREAD

**Issue by Marie-Blr** [CompEvol/beast2#1087]
Hello,
I al having an error with Treeannotator that I am unable to resolve. I am using breast2/2.6.1 and Treeannotator 2.6.0.  Logcombiner succeed to give me an output file, but this one can't be read by treeannotator. Here is the error message I receive : 

Processing 6307 trees from file.
java.io.IOException: Unterminated comment.
	at beast.util.NexusParser.readNexusComment(Unknown Source)
	at beast.util.NexusParser.readNextCommand(Unknown Source)
	at beast.util.NexusParser.parseTaxaBlock(Unknown Source)
	at beast.util.NexusParser.parseFile(Unknown Source)
	at beast.util.NexusParser.parseFile(Unknown Source)
	at beast.app.treeannotator.TreeAnnotator$FastTreeSet.<init>(Unknown Source)
	at beast.app.treeannotator.TreeAnnotator.<init>(Unknown Source)
	at beast.app.treeannotator.TreeAnnotator.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at beast.app.beastapp.BeastLauncher.run(Unknown Source)
	at beast.app.treeannotator.TreeAnnotatorLauncher.main(Unknown Source)
java.io.IOException: Around line 6744
Unterminated comment.
	at beast.util.NFinished - Quit program to exit.
exusParser.parseFile(Unknown Source)
	at beast.util.NexusParser.parseFile(Unknown Source)
	at beast.app.treeannotator.TreeAnnotator$FastTreeSet.<init>(Unknown Source)
	at beast.app.treeannotator.TreeAnnotator.<init>(Unknown Source)
	at beast.app.treeannotator.TreeAnnotator.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at beast.app.beastapp.BeastLauncher.run(Unknown Source)
	at beast.app.treeannotator.TreeAnnotatorLauncher.main(Unknown Source)
Error Parsing Input Tree: Around line 6744
Unterminated comment.

But when I read my .trees file and go to the line 6744, it's the end of the document. 

Thank you a lot for your help ! 

Marie

**Comment by Marie-Blr** [comment]
I hope my answer won't sound too dumb.. I have no "[" in my input .trees file. 
I don't understand how is it possible to have an interminated Nexus comment. Could it be cause by my taxon names, or too low MCMC generations ? 
I have done trees with the same file and all work. The differences between the trees that work and those are some taxa that I have added.
Thank you a lot,
Marie

**Comment by rbouckaert** [comment]
Hi Marie, can you do a quick check to see that the tree file produced by logcombiner starts with a line containing `#NEXUS`? Also, does treeannotator work on any of the un-combined tree files? If so, it may be logcombiner not behaving as expected. Would it be possible to make the combined tree file available?

**Comment by Marie-Blr** [comment]
Hello,

My file starts well with #NEXUS line. Moreover, I recieved the same error when independant un-combined tree files. 
Here is the combined file in the following link (file too big) : https://filesender.renater.fr/?s=download&token=4ef151b6-9b30-4cc4-9183-47b784df7f76
Thank you a lot for helping,
Marie

**Comment by Marie-Blr** [comment]
I feel a little bit durty because I didn't succeed to see it when I red my file.. I will try again by correcting it and will let you know what happen. 
Thank you a lot again,
Marie
