### ISSUE TITLE
TreeAnnotator error: clade.getCount=(92) should be <= totalTreesUsed = (90)

### ISSUE THREAD

**Issue by ekankaka** [CompEvol/beast2#1096]
I want to get a single target tree from 100 trees in a stochastic beast simulation. However, I get the above error (output below). How can i get around it?

>    
              TreeAnnotator v2.7.3, 2002-2022
                    MCMC Output analysis
                             by
           Andrew Rambaut and Alexei J. Drummond

             Institute of Evolutionary Biology
                  University of Edinburgh
                     a.rambaut@ed.ac.uk

               Department of Computer Science
                   University of Auckland
                  alexei@cs.auckland.ac.nz

Processing 90 trees from file after ignoring first 10% = 10 trees.
translation map size = 139

Total number of trees 100, where 90 are used.
Total unique clades: 11325

Finding maximum credibility tree...
Analyzing 90 trees...
0              25             50             75            100
|--------------|--------------|--------------|--------------|
*************************************************************

Highest Log Clade Credibility: -447.40810230811513
Collecting node information...
0              25             50             75            100
|--------------|--------------|--------------|--------------|
*************************************************************Exception in thread "Thread-3" java.lang.AssertionError: clade.getCount=(92) should be <= totalTreesUsed = (90)
	at beastfx.app.treeannotator.CladeSystem.calculateCladeCredibilities(Unknown Source)
	at beastfx.app.treeannotator.TreeAnnotator.<init>(Unknown Source)
	at beastfx.app.treeannotator.TreeAnnotator$2.run(Unknown Source)

**Comment by rbouckaert** [comment]
The error indicates a clade is observed more often than there the number of trees, which suggests something is very wrong with TreeAnnotator or the tree set. Did you create the tree set with BEAST? Would it be possible to make the tree set available for further investigation?

**Comment by ekankaka** [comment]
[model1.zip](https://github.com/CompEvol/beast2/files/11024096/model1.zip)
Yes - created with BEAST (remaster simulation run in beast).
Compressed file attached.

**Comment by rbouckaert** [comment]
Thanks for the file! 

It looks like the tree have single child nodes. TreeAnnotator counts clades below the single child nodes double, which explains the error message: it sees clades more often then there are trees, suggesting over 100% posterior support. TreeAnnotator only deals with binary trees, so it will not be able to summarise the tree set.

Also, trees refer to taxa that are not declared, for example the tree at `STATE_11` refers to node 147, but only 139 taxa are declared, so this does not seem to be a valid NEXUS tree file.

**Comment by ekankaka** [comment]
Great, thanks!
Went back and removed singleton nodes when logging typed trees in remaster.
`        <logger spec="Logger" mode="tree" fileName="$(filebase).typed.tree">
            <log spec="TypedTreeLogger" tree="@poonTree" **removeSingletonNodes="true"**/>
        </logger>`
TreeAnnotator was then able to make a combined tree. 
**Unfortunately**, the combined tree could not be read in Figtree, icytree, or R!
[model1_MCC_medianheights.zip](https://github.com/CompEvol/beast2/files/11031684/model1_MCC_medianheights.zip)

**Comment by ekankaka** [comment]
[model1_noSingletons.zip](https://github.com/CompEvol/beast2/files/11032983/model1_noSingletons.zip)
Attached - input file to TreeAnnotator (with singletons removed)

**Comment by rbouckaert** [comment]
Thanks -- 10% burn-in works because it skips the offending 3rd degree node in the second tree :-)

Maybe you could request for a `binarise` option, to ensure trees produced are always binary trees.

I noticed the input file has more taxa than the output file. What is unusual is that the taxon numbers are not consecutive any more and commas stop after taxon number exceeds the total number of taxa as declared at the start of the treeannotator output in NEXUS format. This explains the missing commas, but I'll have to investigate why the taxon numbers are not consecutive any more.

**Comment by ekankaka** [comment]
Noted, thanks!
