### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by lecorguille** [CompEvol/beast2#1105]
I'm trying to install Beast2 on our HPC infrastructure.
We only rely on Conda and Singularity/Apptainer to deploy the tools.

The conda package is rather old and my naive attempt (bump of the version) to update it just failed. It seems to be a gap between the 2.6.x and the 2.7.x

So my second choice is Singularity/Apptainer: [Install singularity/beast2/2.7.3](https://gitlab.com/ifb-elixirfr/cluster/tools/-/merge_requests/1065)

The singularity definition file is here : [image.def](https://gitlab.com/ifb-elixirfr/cluster/tools/-/blob/beast/tools/beast2/2.7.3/image.def)

How to reproduce
```bash
wget https://gitlab.com/ifb-elixirfr/cluster/tools/-/raw/beast/tools/beast2/2.7.3/image.def
apptainer build image.sif image.def
```

```
[...]
INFO:    Adding environment to container
INFO:    Adding testscript
INFO:    Running testscript
Error: Could not find or load main class beast.pkgmgmt.launcher.BeastLauncher
Caused by: java.lang.ClassNotFoundException: beast.pkgmgmt.launcher.BeastLauncher
FATAL:   While performing build: failed to execute %test script: exit status 1
```

The full log here: 
https://gitlab.com/ifb-elixirfr/cluster/tools/-/jobs/4067809453#L2260

It's maybe just a PATH, a env variable or a file that isn't well positionned?
Can you advice me? I'm not experimented in Java.

**Comment by rbouckaert** [comment]
I am not familiar with Singularity/Aptainer, so am not completely sure where to look. The `ClassNotFoundException` in the log you referred to suggests that the java class path is not set up. The minimum command should work is

`java -cp /path/to/beast/bin/launcher.jar beast.pkgmgmt.launcher.BeastLauncher`

that is, the `-cp` defines the class path pointing to `/path/to/beast/bin/launcher.jar`, and `launcher.jar` file contains the `BeastLaucher` class. The script used to start BEAST should (`/path/to/beast/bin/beast`) uses the `BEAST` environment variable to define the class path as `$BEAST/lib`. So, perhaps setting up that to point to `/path/to/beast` is sufficient to make it run.

BEAST is based on Java17 and all GUIs are JavaFX based. Because of the way modules now make things uncomfortable, it is recommended to use the JDK with JavaFX included from [Azul](https://www.azul.com/downloads/?version=java-17-lts&os=linux&package=jre-fx) for x86 or [Bellsoft](https://bell-sw.com/pages/downloads/) for arm based systems. BEAST may work with other JDKs but may require more configurating.

**Comment by lecorguille** [comment]
Thanks a bunch for your quick reply

```
lecorguille@n75:~/singularity_build/beast2# apptainer shell image.sif

Apptainer> echo $BEAST
/usr/local/beast2
Apptainer> beast
Error: Could not find or load main class beast.pkgmgmt.launcher.BeastLauncher
Caused by: java.lang.ClassNotFoundException: beast.pkgmgmt.launcher.BeastLauncher

Apptainer> export BEAST=/usr/local/beast2/lib/
Apptainer> beast
Error: Could not find or load main class beast.pkgmgmt.launcher.BeastLauncher
Caused by: java.lang.ClassNotFoundException: beast.pkgmgmt.launcher.BeastLauncher

```

The `BEAST` environment variable seems already setted.

Can you check with me the contain of /usr/local/beast2/ ?

```
Apptainer> ls /usr/local/beast2/*
/usr/local/beast2/bin:
applauncher  beast  beauti  densitree  loganalyser  logcombiner  packagemanager  treeannotator

/usr/local/beast2/lib:
BEAST.base.jar
```

**Comment by lecorguille** [comment]
> BEAST is based on Java17 and all GUIs are JavaFX based. Because of the way modules now make things uncomfortable, it is recommended to use the JDK with JavaFX included from [Azul](https://www.azul.com/downloads/?version=java-17-lts&os=linux&package=jre-fx) for x86 or [Bellsoft](https://bell-sw.com/pages/downloads/) for arm based systems. BEAST may work with other JDKs but may require more configurating.

Is it those packages: https://docs.azul.com/core/zulu-openjdk/install/debian ?
Something like that : `https://cdn.azul.com/zulu/bin/zulu17.40.19-ca-jdk17.0.6-linux_amd64.deb` ?

**Comment by rbouckaert** [comment]
The `/usr/localb/beast2/lib` folder should contain `DensiTree.jar		launcher.jar		launcher.src.jar	packages` where `packages` is a folder. The crucial `launcher.jar` seems to be missing, which explains the `ClassNotFoundException` error you mentioned earlier. Getting the `launcher.jar` file back in place may fix your problem.

Also, BEAST2 is released with the JRE included, and there should be a `/usr/localb/beast2/jre` directory, but your `ls` command does not show this. If you want to install the JDK separately, make sure to take the version that has JavaFX included: https://www.azul.com/downloads/?version=java-17-lts&os=debian&package=jdk-fx#zulu, not the JDK alone.

**Comment by lecorguille** [comment]
> I am not familiar with Singularity/Aptainer, so am not completely sure where to look.
Rather easy. From `%post`, it's like bash command.

But I'm sorry but I can't find launcher.jar.
Do you have somewhere some instructions how to build and install Beasts and BeastFX that need to be requested?

My first plan was to build from source.

But I also try to use [the pre-built version](https://github.com/CompEvol/beast2/releases/download/v2.7.4/BEAST.v2.7.4.Linux.x86.tgz) but 
```
saveBeautiProperty java.io.IOException No such file or directory
java.lang.ClassNotFoundException: beastfx.app.beast.BeastMain
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at beast.pkgmgmt.BEASTClassLoader.forName(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.run(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.main(Unknown Source)
```

My apology but one of my user really need Beast2 within the next few days.

**Comment by rbouckaert** [comment]
Would this be an option:
* download the BEAST release from [here](https://github.com/CompEvol/beast2/releases/download/v2.7.4/BEAST.v2.7.4.Linux.x86.tgz) for Linux x86 (an aarch64 version is [here](https://github.com/CompEvol/beast2/releases/download/v2.7.4/BEAST.v2.7.4.Linux.aarch64.tgz)).
*  uncompress the archive in `/usr/local/`, which creates `/usr/local/beast`
* optionally, rename `/usr/local/beast/` to `/usr/local/beast2` if that is what you need.
* add `/usr/local/beast/bin` to the user's path.

The release is self-contained, and the `beast` script in `/usr/local/beast/bin/beast` should be able to pick up the appropriate JRE from `/usr/local/beast/jre` and `launcher.jar` is includes in `/usr/local/beast/lib` so it should work

**Comment by rbouckaert** [comment]
The `saveBeautiProperty` error message indicates that the `beauti.properties` file cannot be written, which is a file containing some properties such as the last working directory. Normally, this is quite harmless.
It can happen when the user package directory, which is `~/.beast/2.7` by default in Linux, does not exist yet. The directory should be created the first time BEAST is run, e.g. by running `beast -version`

**Comment by lecorguille** [comment]
It works !
My original plan was to compile from source in order to allow the use of GPU (through beagle).
But since the time is running, the pre-built release is ok.

**Comment by lecorguille** [comment]
It should be cool to provide a Docker or a Apptainer/Singularity definition file.

https://gitlab.com/ifb-elixirfr/cluster/tools/-/blob/master/tools/beast2/2.7.4/image.def

**Comment by lecorguille** [comment]
I'm back
In order to install packages, it seems that we need to launch `beauti`.

When I launch it:
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.run(Unknown Source)
	at beast.pkgmgmt.launcher.BeautiLauncher.main(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: Internal Error
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.<init>(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.Application.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[lecorguille@slurm0 ~]$ rm -rf ~/.beast/
[lecorguille@slurm0 ~]$ /tmp/image.new.sif beauti
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.run(Unknown Source)
	at beast.pkgmgmt.launcher.BeautiLauncher.main(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: Internal Error
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.<init>(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.Application.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

It eventuelly open the graphic interface and propose me to install/update `ORC`, `BEASTLabs`, `starbeast3`, `SA`.
When I click I get:
```
Installed ORC in /home/fr2424/sib/lecorguille/.beast/2.7/ORC
Installed BEASTLabs in /home/fr2424/sib/lecorguille/.beast/2.7/BEASTLabs
Installed starbeast3 in /home/fr2424/sib/lecorguille/.beast/2.7/starbeast3
Installed SA in /home/fr2424/sib/lecorguille/.beast/2.7/SA
```
Then nothing

If I rerun beauti, I get the same error but nothing pop.

Any idea?

**Comment by rbouckaert** [comment]
Packages can be installed using the package manager -- this can be done via BEAUti, which is what we recommend for most users, but it can also be done via the command line: `/usr/local/beast/bin/packagemanager -help` shows the list of available options for listing, installing and removing etc. packages.

Not sure how to interpret the error message: it seems to indicate something is wrong with the display. Can you run BEAST, for example `/usr/loca/beast/bin/beast -seed 123 /usr/local/beast/examples/testHKY.xml`?

**Comment by lecorguille** [comment]
beast seems ok according to my colleague.
I didn't know for packagemanager, it will do the trick!

**Comment by rbouckaert** [comment]
Great to hear that! I suppose this issue can remain closed.
