### ISSUE TITLE
BEAUTI frozen: sb3TREEPriors

### ISSUE THREAD

**Issue by starsareintherose** [CompEvol/beast2#1107]
![image](https://user-images.githubusercontent.com/37733075/234087430-2e16ba6a-1f21-4fb0-b93e-4d761e2d85cd.png)

 - OS: Arch Linux
 - version: 2.7.4

```
[0.003s][warning][cds] A jar file is not the one used while building the shared archive file: /usr/lib/jvm/java-20-openjdk/lib/modules
[0.003s][warning][cds] /usr/lib/jvm/java-20-openjdk/lib/modules timestamp has changed.
java.lang.NullPointerException: Cannot invoke "java.io.InputStream.close()" because "<local2>" is null
	at beast.pkgmgmt.launcher.BeastLauncher.copyFileUsingStream(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.createBeastPackage(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.installBEASTPackage(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.getPath(Unknown Source)
	at beast.pkgmgmt.launcher.BeautiLauncher.main(Unknown Source)
Loading package starbeast3 v1.1.7 SA v2.1.1 BEASTLabs v2.0.0 ORC v1.1.1 BEAST.app v2.7.4    
java.lang.NoSuchMethodException: sa.beauti.SampledNodeDataWalkerInputEditor.<init>(beastfx.app.inputeditor.BeautiDoc)
java.lang.NullPointerException: Cannot invoke "java.io.InputStream.close()" because "<local2>" is null
	at beast.pkgmgmt.launcher.BeastLauncher.copyFileUsingStream(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.createBeastPackage(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.installBEASTPackage(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.getPath(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.processTemplate(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.mergeSequences(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.initialize(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.parseArgs(Unknown Source)
	at beastfx.app.beauti.BeautiTabPane.initialise(Unknown Source)
	at beastfx.app.beauti.Beauti$2.call(Unknown Source)
	at beastfx.app.beauti.Beauti$2.call(Unknown Source)
	at javafx.graphics@20.0.1-internal/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Loading template /home/guoyi/.beast/2.7/BEAST.app/fxtemplates/Standard.xml
Investigating 
Investigating /home/guoyi/.beast/2.7/BEASTLabs
Processing /home/guoyi/.beast/2.7/BEASTLabs/fxtemplates/extras.xml
Processing /home/guoyi/.beast/2.7/BEASTLabs/fxtemplates/Weibull.xml
Investigating /home/guoyi/.beast/2.7/SA
Processing /home/guoyi/.beast/2.7/SA/fxtemplates/FBD.xml
Investigating /home/guoyi/.beast/2.7/ORC
Processing /home/guoyi/.beast/2.7/ORC/fxtemplates/OptimisedRelaxedClock.xml
Investigating /home/guoyi/.beast/2.7/BEAST.app
Processing /home/guoyi/.beast/2.7/BEAST.app/fxtemplates/ClockModels.xml
Processing /home/guoyi/.beast/2.7/BEAST.app/fxtemplates/TreePriors.xml
Processing /home/guoyi/.beast/2.7/BEAST.app/fxtemplates/SubstModels.xml
Processing /home/guoyi/.beast/2.7/BEAST.app/fxtemplates/ParametricDistributions.xml
Investigating .
Investigating /usr/share/beast2
Skipping /usr/share/beast2/fxtemplates/ClockModels.xml since ClockModels.xml is already processed
Processing /usr/share/beast2/fxtemplates/Standard.xml
Skipping /usr/share/beast2/fxtemplates/TreePriors.xml since TreePriors.xml is already processed
Skipping /usr/share/beast2/fxtemplates/SubstModels.xml since SubstModels.xml is already processed
Skipping /usr/share/beast2/fxtemplates/ParametricDistributions.xml since ParametricDistributions.xml is already processed
Investigating /home/guoyi/.beast/2.7/starbeast3
Processing /home/guoyi/.beast/2.7/starbeast3/fxtemplates/StarBeast3.xml
Processing /home/guoyi/.beast/2.7/starbeast3/fxtemplates/sb3ClockModelTemplates.xml
Cannot find merge point named sb3ClockModelTemplates from sb3ClockModelTemplates.xml in template. MergeWith ignored.
Processing /home/guoyi/.beast/2.7/starbeast3/fxtemplates/sb3SubstModels.xml
Cannot find merge point named sb3SubstModelTemplates from sb3SubstModels.xml in template. MergeWith ignored.
Processing /home/guoyi/.beast/2.7/starbeast3/fxtemplates/sb3TreePriors.xml
Cannot find merge point named sb3TreePriorTemplates from sb3TreePriors.xml in template. MergeWith ignored.
connect => beastfx.app.inputeditor.BeautiConnector
subtemplate => beastfx.app.inputeditor.BeautiSubTemplate
map
map
map
map
map
map
map
map
map
map
map
map
beauticonfig
fragment
run
java.lang.ClassNotFoundException: Could not find class beast.base.inference.MCMC as service beast.base.core.BEASTInterface
Perhaps the package is missing or the package is not correctly configured by the developer (Developer: check by running beastfx.app.tools.PackageHealthChecker on the package)
	at beast.pkgmgmt.BEASTClassLoader.forName(Unknown Source)
	at beast.base.parser.XMLParser.createObject(Unknown Source)
	at beast.base.parser.XMLParser.parseTemplate(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.loadTemplate(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.mergeSequences(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.initialize(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.parseArgs(Unknown Source)
	at beastfx.app.beauti.BeautiTabPane.initialise(Unknown Source)
	at beastfx.app.beauti.Beauti$2.call(Unknown Source)
	at beastfx.app.beauti.Beauti$2.call(Unknown Source)
	at javafx.graphics@20.0.1-internal/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1623)

```

**Comment by rbouckaert** [comment]
The log does not seem to load `BEAST.base v2.7.4` (though does load `BEAST.app v2.7.4`), which suggests something may have gone wrong with the package directory. Perhaps the easiest way to fix this is to remove the BEAST package directory (`rm -r ~/.beast/2.7`) and install the packages again. Let me know if the problem persists.

**Comment by starsareintherose** [comment]
I have tried to do so, already, before rm this, it is frozen at other words

**Comment by rbouckaert** [comment]
How did you install BEAST 2? There are 2 versions for Linux at the [release](https://github.com/CompEvol/beast2/releases) page: one for x86 and one for arm. The error message refers to java20, but BEAST 2 should run under Java 17 included in the release. Using other versions of Java requires JavaFX to be available, and potentially some extra command line options to get BEAST and BEAUti going to deal with modules.

**Comment by starsareintherose** [comment]
I compile it from source, let me try 17 firstly

**Comment by starsareintherose** [comment]
When I changed, it is still

```
java.lang.NullPointerException: Cannot invoke "java.io.InputStream.close()" because "<local2>" is null
	at beast.pkgmgmt.launcher.BeastLauncher.copyFileUsingStream(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.createBeastPackage(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.installBEASTPackage(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.getPath(Unknown Source)
	at beast.pkgmgmt.launcher.BeautiLauncher.main(Unknown Source)
Loading package starbeast3 v1.1.7 SA v2.1.1 BEASTLabs v2.0.0 ORC v1.1.1 BEAST.app v2.7.4    
java.lang.NoSuchMethodException: sa.beauti.SampledNodeDataWalkerInputEditor.<init>(beastfx.app.inputeditor.BeautiDoc)
java.lang.NullPointerException: Cannot invoke "java.io.InputStream.close()" because "<local2>" is null
	at beast.pkgmgmt.launcher.BeastLauncher.copyFileUsingStream(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.createBeastPackage(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.installBEASTPackage(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.getPath(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.processTemplate(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.mergeSequences(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.initialize(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.parseArgs(Unknown Source)
	at beastfx.app.beauti.BeautiTabPane.initialise(Unknown Source)
	at beastfx.app.beauti.Beauti$2.call(Unknown Source)
	at beastfx.app.beauti.Beauti$2.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Loading template /home/guoyi/.beast/2.7/BEAST.app/fxtemplates/Standard.xml
Investigating 
Investigating /home/guoyi/.beast/2.7/BEASTLabs
Processing /home/guoyi/.beast/2.7/BEASTLabs/fxtemplates/extras.xml
Processing /home/guoyi/.beast/2.7/BEASTLabs/fxtemplates/Weibull.xml
Investigating /home/guoyi/.beast/2.7/SA
Processing /home/guoyi/.beast/2.7/SA/fxtemplates/FBD.xml
Investigating /home/guoyi/.beast/2.7/ORC
Processing /home/guoyi/.beast/2.7/ORC/fxtemplates/OptimisedRelaxedClock.xml
Investigating /home/guoyi/.beast/2.7/BEAST.app
Processing /home/guoyi/.beast/2.7/BEAST.app/fxtemplates/ClockModels.xml
Processing /home/guoyi/.beast/2.7/BEAST.app/fxtemplates/TreePriors.xml
Processing /home/guoyi/.beast/2.7/BEAST.app/fxtemplates/SubstModels.xml
Processing /home/guoyi/.beast/2.7/BEAST.app/fxtemplates/ParametricDistributions.xml
Investigating .
Investigating /usr/share/beast2
Skipping /usr/share/beast2/fxtemplates/ClockModels.xml since ClockModels.xml is already processed
Processing /usr/share/beast2/fxtemplates/Standard.xml
Skipping /usr/share/beast2/fxtemplates/TreePriors.xml since TreePriors.xml is already processed
Skipping /usr/share/beast2/fxtemplates/SubstModels.xml since SubstModels.xml is already processed
Skipping /usr/share/beast2/fxtemplates/ParametricDistributions.xml since ParametricDistributions.xml is already processed
Investigating /home/guoyi/.beast/2.7/starbeast3
Processing /home/guoyi/.beast/2.7/starbeast3/fxtemplates/StarBeast3.xml
Processing /home/guoyi/.beast/2.7/starbeast3/fxtemplates/sb3ClockModelTemplates.xml
Cannot find merge point named sb3ClockModelTemplates from sb3ClockModelTemplates.xml in template. MergeWith ignored.
Processing /home/guoyi/.beast/2.7/starbeast3/fxtemplates/sb3SubstModels.xml
Cannot find merge point named sb3SubstModelTemplates from sb3SubstModels.xml in template. MergeWith ignored.
Processing /home/guoyi/.beast/2.7/starbeast3/fxtemplates/sb3TreePriors.xml
Cannot find merge point named sb3TreePriorTemplates from sb3TreePriors.xml in template. MergeWith ignored.
connect => beastfx.app.inputeditor.BeautiConnector
subtemplate => beastfx.app.inputeditor.BeautiSubTemplate
map
map
map
map
map
map
map
map
map
map
map
map
beauticonfig
fragment
run
java.lang.ClassNotFoundException: Could not find class beast.base.inference.MCMC as service beast.base.core.BEASTInterface
Perhaps the package is missing or the package is not correctly configured by the developer (Developer: check by running beastfx.app.tools.PackageHealthChecker on the package)
	at beast.pkgmgmt.BEASTClassLoader.forName(Unknown Source)
	at beast.base.parser.XMLParser.createObject(Unknown Source)
	at beast.base.parser.XMLParser.parseTemplate(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.loadTemplate(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.mergeSequences(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.initialize(Unknown Source)
	at beastfx.app.inputeditor.BeautiDoc.parseArgs(Unknown Source)
	at beastfx.app.beauti.BeautiTabPane.initialise(Unknown Source)
	at beastfx.app.beauti.Beauti$2.call(Unknown Source)
	at beastfx.app.beauti.Beauti$2.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by rbouckaert** [comment]
Thanks for the suggestion of using sub-modules -- will look into that.

This line:

```Loading package starbeast3 v1.1.7 SA v2.1.1 BEASTLabs v2.0.0 ORC v1.1.1 BEAST.app v2.7.4    ```

still suggests that the `BEAST.base` package is not loaded. That is the packages that contains the class `beast.base.inference.MCMC` which is reported to be missing.

When building from source, are you using ant? The way to build the Linux release is to use `ant linux` in the `BeastFX` directory. You may need to change the `build.xml` file to change the `openjreLnx` property to point to where you have your jre.

**Comment by starsareintherose** [comment]
Yeah, see 
```
 ant linux -nouserlib -noinput \
        -Drelease_dir=release2 \
        -Dbeast2="../${pkgname}-${pkgver}" \
        -Dbeast2path="../${pkgname}-${pkgver}" \
        -lib "/usr/lib/jvm/default-runtime/lib" \
        -Dcommon_dir="../${pkgname}-${pkgver}/release/common/" \
        -DopenjreLnx="/usr/lib/jvm/default/" \
        -DBEASTappName="BeastFX-${pkgver}" \
        -DBeastFX="BeastFX-${pkgver}"
```

**Comment by rbouckaert** [comment]
`ant linux` should be sufficient. Perhaps any of the other options cause the problem. I suspect the `BEAST.base` package goes missing somehow.

The release directory (by default `beast2/release/Linux/beast`) should contain theses files in the `lib` folder:

```
lib/launcher.jar
lib/DensiTree.jar
lib/packages
lib/packages/BEAST.base.version.xml
lib/packages/BEAST.app.jar
lib/packages/BEAST.base.src.jar
lib/packages/BEAST.app.version.xml
lib/packages/BEAST.base.jar
lib/packages/BEAST.app.src.jar
lib/launcher.src.jar
```

Can you check you get the same set of file?

**Comment by starsareintherose** [comment]
I can sure that they are absent.

**Comment by rbouckaert** [comment]
Do they appear in `beast2/release/Linux/beast/lib` when you run `ant linux` from the `BeastFX` directory?

**Comment by starsareintherose** [comment]
Only found these 
```
./build/dist/launcher.jar
./release/common/tools/DensiTree.jar
./build/dist/BEAST.base.src.jar
./build/dist/BEAST.base.jar
./build/dist/launcher.src.jar
```

**Comment by rbouckaert** [comment]
What output do you get when running `ant linux` from the `BeastFX` directory?

**Comment by starsareintherose** [comment]
@sukanka Could you help solve it? I am not sure, seems some error, this is the build log https://build.bioarchlinux.org/api/pkg/beast2/log/1682451473

**Comment by sukanka** [comment]
> @sukanka Could you help solve it? I am not sure, seems some error, this is the build log https://build.bioarchlinux.org/api/pkg/beast2/log/1682451473

Ok, I'll have a look when I finish my work.

**Comment by rbouckaert** [comment]
These lines:

```
     [exec] tar: beast: Cannot stat: No such file or directory
     [exec] tar: Exiting with failure status due to previous errors
```

suggest that the tar job is looking at the wrong place.

Out of curiosity, why do you want build from source instead of using the released binaries?

**Comment by starsareintherose** [comment]
Yeah, I see. This is a bio repo for archlinux, almost all things should be build from source, or it's close source software. Though we have about less than 5 pkg not built from source, we are trying to do so.

**Comment by rbouckaert** [comment]
Even if the tar command is fixed, there still will be a problem. This is the output I get from `ant linux`:

```
   [delete] Deleting directory /Users/remco/workspace/beast2/release/Linux/beast
    [mkdir] Created dir: /Users/remco/workspace/beast2/release/Linux/beast
     [copy] Copying 8 files to /Users/remco/workspace/beast2/release/Linux/beast/bin
     [copy] Copying 76 files to /Users/remco/workspace/beast2/release/Linux/beast/examples
     [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/images
     [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/images
     [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib
     [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib
     [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib/packages
     [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib/packages
     [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib/packages
     [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib/packages
     [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib/packages
     [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib/packages
     [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib
     [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/images
     [copy] Copying 6 files to /Users/remco/workspace/beast2/release/Linux/beast/fxtemplates
     [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast
     [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast
     [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast
     [echo] Linux/Unix version release is finished as /Users/remco/workspace/beast2/release/Linux/BEAST.v2.7.4.tgz.
```


Note the 6 lines that copy into `/Users/remco/workspace/beast2/release/Linux/beast/lib/packages` while the output you referred to copy them into `/build/beast2/src/BeastFX-2.7.4/release2/Linux/beast//lib`. Since the launcher installs the BEAST.base and BEAST.app packages by copying them from the `beast/lib/packages` directory, it won't be able to find them. This explains why the `BEAST.base` package was not loaded. Fixing the copy command might fix the problem (the tar issue is just compressing things in a single file, but should not prevent you from running BEAUti from `build/beast2/src/BeastFX-2.7.4/release2/Linux/beast/`.

**Comment by sukanka** [comment]
> Even if the tar command is fixed, there still will be a problem. This is the output I get from `ant linux`:
> 
> ```
>    [delete] Deleting directory /Users/remco/workspace/beast2/release/Linux/beast
>     [mkdir] Created dir: /Users/remco/workspace/beast2/release/Linux/beast
>      [copy] Copying 8 files to /Users/remco/workspace/beast2/release/Linux/beast/bin
>      [copy] Copying 76 files to /Users/remco/workspace/beast2/release/Linux/beast/examples
>      [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/images
>      [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/images
>      [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib
>      [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib
>      [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib/packages
>      [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib/packages
>      [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib/packages
>      [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib/packages
>      [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib/packages
>      [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib/packages
>      [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/lib
>      [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast/images
>      [copy] Copying 6 files to /Users/remco/workspace/beast2/release/Linux/beast/fxtemplates
>      [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast
>      [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast
>      [copy] Copying 1 file to /Users/remco/workspace/beast2/release/Linux/beast
>      [echo] Linux/Unix version release is finished as /Users/remco/workspace/beast2/release/Linux/BEAST.v2.7.4.tgz.
> ```
> 
> Note the 6 lines that copy into `/Users/remco/workspace/beast2/release/Linux/beast/lib/packages` while the output you referred to copy them into `/build/beast2/src/BeastFX-2.7.4/release2/Linux/beast//lib`. Since the launcher installs the BEAST.base and BEAST.app packages by copying them from the `beast/lib/packages` directory, it won't be able to find them. This explains why the `BEAST.base` package was not loaded. Fixing the copy command might fix the problem (the tar issue is just compressing things in a single file, but should not prevent you from running BEAUti from `build/beast2/src/BeastFX-2.7.4/release2/Linux/beast/`.

Thanks for your patience！ I've just verified that. In 2.7.4, `BEAST.app` and `BEAST.base` should be put in another directory called `packages`. After fixing the problem, I'm now able to run `beast2-beauti`.

![image](https://user-images.githubusercontent.com/31362108/234886116-989e22b6-55cf-4c00-a499-b949e47bcdf0.png)

**Comment by starsareintherose** [comment]
Thanks again, this has been solved

**Comment by rbouckaert** [comment]
No problem. I had a quick look at git submodules, but it seems to require reconfiguration for existing developers, so seems more trouble than it is worth. However, tagging beast2 and BeastFX at the same time makes sense. For future major releases (v2.8), it probably makes sense to merge beast2 and BeastFX into a single repo again, which would solve the synchronisation problem more gracefully.
