### ISSUE TITLE
.xml.state not found

### ISSUE THREAD

**Issue by kesiaeds** [CompEvol/beast2#1146]
Dear all I am trying to run BEAST2 2.6 version and I keep getting this err message. The full log file and xml file is attached. I would really apppreciate if you could help me figure out what is the problem.
[slurm-4281671.txt](https://github.com/CompEvol/beast2/files/14842254/slurm-4281671.txt)
[cluster9.old.fixed.w.xml.zip](https://github.com/CompEvol/beast2/files/14842269/cluster9.old.fixed.w.xml.zip)
[cluster9.old.w.xml.zip](https://github.com/CompEvol/beast2/files/14842272/cluster9.old.w.xml.zip)

Restoring from file
File error: /oak/stanford/scg/lab_jandr/Kesia/TB/tb_genomics/study/cluster/BEAST/cluster9.old.fixed.w.xml.state (No such file or directory)
java.lang.RuntimeException: An error was encounted. Terminating BEAST
	at beast.app.util.ErrorLogHandler.publish(Unknown Source)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at java.util.logging.Logger.severe(Logger.java:1464)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at beast.app.beastapp.BeastLauncher.run(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)

**Comment by zyy-1111** [comment]
have you fixed it?I met the same problem

**Comment by rbouckaert** [comment]
This can happen when the state file moved. First thing to do is check whether the file that is missing is somewhere else. If so, start beast with the `--statefile` option, like so:
```
beast -statefile /path/to/where/the/state/file/is/beast.xml.state -resume beast.xml
```
where ` /path/to/where/the/state/file/is/` the path to where the state file is.

**Comment by zyy-1111** [comment]
I tried chaning it, but still can't work.







At 2024-06-20 04:31:03, "Remco Bouckaert" ***@***.***> wrote:

This can happen when the state file moved. First thing to do is check whether the file that is missing is somewhere else. If so, start beast with the --statefile option, like so:

beast -statefile /path/to/where/the/state/file/is/beast.xml.state -resume beast.xml


where /path/to/where/the/state/file/is/ the path to where the state file is.

**Comment by zyy-1111** [comment]
Could u share a xml file that can run successfully?

**Comment by rbouckaert** [comment]
Any of the [example files](https://github.com/CompEvol/beast2/tree/master/examples) that come with BEAST should run.
