### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "beast.base.evolution.tree.Node.getNr()" because "<local7>" is null

### ISSUE THREAD

**Issue by CiaccioE** [CompEvol/beast2#1170]
Hello,

I am trying to run an FBD dating analysis with StarBEAST3 (1.1.9) on BEAST 2.7.5 and I keep having an error I cannot find anywhere on google groups or github. I'm not sure what this error is pointing to. I have done divergence dating with this dataset using a Yule model, however I want to try an FBD model now.

I have attached my XML file (as .txt, for some reason github is not happy with XML)

[Hypo6_run5_test.xml.txt](https://github.com/user-attachments/files/17482280/Hypo6_run5_test.xml.txt)

The error is a NullPointerException error as the title states. Any help would be greatly appreciated! Thanks,

Erik

java.lang.NullPointerException: Cannot invoke "beast.base.evolution.tree.Node.getNr()" because "<local7>" is null
	at starbeast3.evolution.speciation.GeneTreeForSpeciesTreeDistribution.update(Unknown Source)
	at starbeast3.evolution.speciation.GeneTreeForSpeciesTreeDistribution.mapGeneNodeToSpeciesNode(Unknown Source)
	at starbeast3.core.StarBeastStartState.resetGeneTreeTipHeights(Unknown Source)
	at starbeast3.core.StarBeastStartState.initStateNodes(Unknown Source)
	at beast.base.inference.MCMC.run(Unknown Source)
	at beastfx.app.beast.BeastMCMC.run(Unknown Source)
	at beastfx.app.beast.BeastMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.run(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.main(Unknown Source)

**Comment by rbouckaert** [comment]
@CiaccioE it looks like there is an alignment for the fossil that only has a single taxon (namely Cretacattyma_raveni_fossil1_gene). As a consequence, a tree with 1 node is created, which leads to the problem.

To fix this, the sequence alignment must be extended with a single sequence for Cretacattyma_raveni_fossil1_gene with all sites unknown (question marks) before importing into BEAUti. I edited the XML you posted and removed all references to the gene tree with only the Cretacattyma_raveni_fossil1_gene in it, and it seems to have solved the problem.

[Hypo6_run5_test.xml.txt](https://github.com/user-attachments/files/17483404/Hypo6_run5_test.xml.txt)

Cheers, Remco

**Comment by rbouckaert** [comment]
Great to hear that, Erik! 
I'll close the issue then, but you can reopen if the problem reappears.
