### ISSUE TITLE
OutOfMemoryException in TreeAnnotator

### ISSUE THREAD

**Issue by pedroreys** [CompEvol/beast2#150]
Hey folks,

I generated a tree using an old version of BEAST (1.8) that is available in [CIPRES](http://www.phylo.org/).

Now, when I try to run TreeAnnotator (I'm using the latest release I found on beast2.org) using that tree as the input, when it gets to 50% in the progress bar an OutOfMemory Exception is thrown.

Is there anything that I can do to prevent it from happening?

Thanks!

Here is the log with the stack trace:

```

       TreeAnnotator v2.1.2 Prerelease r$, 2002-2014
                    MCMC Output analysis
                             by
           Andrew Rambaut and Alexei J. Drummond

             Institute of Evolutionary Biology
                  University of Edinburgh
                     a.rambaut@ed.ac.uk

               Department of Computer Science
                   University of Auckland
                  alexei@cs.auckland.ac.nz


*0              25             50             75            100
|--------------|--------------|--------------|--------------|
*******************************[LaunchRunner Error] beast.app.treeannotator.TreeAnnotator.main(String[]) threw an exception:
java.lang.OutOfMemoryError: Java heap space
    at sun.misc.FDBigInt.<init>(FloatingDecimal.java:2415)
    at sun.misc.FloatingDecimal.doubleValue(FloatingDecimal.java:1509)
    at sun.misc.FloatingDecimal.floatValue(FloatingDecimal.java:1729)
    at java.lang.Float.parseFloat(Float.java:422)
    at beast.app.treeannotator.TreeSetParser.parseNewick(Unknown Source)
    at beast.app.treeannotator.TreeSetParser.parseFile(Unknown Source)
    at beast.app.treeannotator.TreeAnnotator.<init>(Unknown Source)
    at beast.app.treeannotator.TreeAnnotator.main(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at apple.launcher.LaunchRunner.run(LaunchRunner.java:116)
    at apple.launcher.LaunchRunner.callMain(LaunchRunner.java:51)
    at apple.launcher.JavaApplicationLauncher.launch(JavaApplicationLauncher.java:52)
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:276)
    at java.awt.Component.firePropertyChange(Component.java:8287)
    at javax.swing.JComponent.putClientProperty(JComponent.java:4047)
    at com.apple.laf.AquaRootPaneUI.updateComponentTreeUIActivation(AquaRootPaneUI.java:285)
    at com.apple.laf.AquaRootPaneUI.updateComponentTreeUIActivation(AquaRootPaneUI.java:299)
    at com.apple.laf.AquaRootPaneUI.updateComponentTreeUIActivation(AquaRootPaneUI.java:299)
    at com.apple.laf.AquaRootPaneUI.updateComponentTreeUIActivation(AquaRootPaneUI.java:299)
    at com.apple.laf.AquaRootPaneUI.updateComponentTreeUIActivation(AquaRootPaneUI.java:299)
    at com.apple.laf.AquaRootPaneUI.updateComponentTreeUIActivation(AquaRootPaneUI.java:299)
    at com.apple.laf.AquaRootPaneUI.windowDeactivated(AquaRootPaneUI.java:261)
    at java.awt.AWTEventMulticaster.windowDeactivated(AWTEventMulticaster.java:382)
    at java.awt.Window.processWindowEvent(Window.java:1889)
    at javax.swing.JFrame.processWindowEvent(JFrame.java:274)
    at java.awt.Window.processEvent(Window.java:1832)
    at java.awt.Component.dispatchEventImpl(Component.java:4776)
    at java.awt.Container.dispatchEventImpl(Container.java:2142)
    at java.awt.Window.dispatchEventImpl(Window.java:2492)
    at java.awt.Component.dispatchEvent(Component.java:4604)
    at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1856)
    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:920)
    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:602)
    at java.awt.Component.dispatchEventImpl(Component.java:4648)
    at java.awt.Container.dispatchEventImpl(Container.java:2142)
    at java.awt.Window.dispatchEventImpl(Window.java:2492)
    at java.awt.Component.dispatchEvent(Component.java:4604)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
```

**Comment by thayan4** [comment]
Hi guys. I'm running my data with BEAST v1.7.5 on WINDOWS and have encountered the same problem. 

This is what I get:

Highest Log Clade Credibility: -213.5097733856253
Collecting node information...
0              25             50             75            100
|--------------|--------------|--------------|--------------|
**********************************Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.util.Arrays.copyOf(Unknown Source)
	at java.util.ArrayList.grow(Unknown Source)
	at java.util.ArrayList.ensureExplicitCapacity(Unknown Source)
	at java.util.ArrayList.ensureCapacityInternal(Unknown Source)
	at java.util.ArrayList.add(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributesForClade(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator$CladeSystem.collectAttributes(Unknown Source)
	at dr.app.tools.TreeAnnotator.<init>(Unknown Source)
	at dr.app.tools.TreeAnnotator.main(Unknown Source)

What should I do?

**Comment by tgvaughan** [comment]
Hi @thayan4, this is issue (and project) is specific to BEAST 2.x.  In general it's probably best to direct these sorts of questions to the beast-users mailing list which can be found at http://groups.google.com/group/beast-users.  That said, it sounds like you may need to simply give Java a bit more memory to play with.  [This page](http://beast.bio.ed.ac.uk/Increasing-Memory-Usage) gives instructions on how to do this in BEAST 1.x.
