### ISSUE TITLE
NexusParser should support the Standard datatype, including ambiguities

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#157]
BEAUti fails in general to parse nexus files with the standard datatype. For example this one:

http://purl.org/phylo/treebase/phylows/matrix/TB2:M3982?format=nexus

At least one problem seems to be an inability to parse ambiguities in the sequences, which are defined by a set of states enclosed in curly brackets. For example the matrix of the first 3 taxa in the file above looks like:

Anolis_acutus                   0021021134507100
Anolis_aeneus                   0000011134306100
Anolis_agassizi                 0000011134306100
Anolis_ahli                     002104113{34}{56}08211

As you can see the "sequence string" of the fourth taxa contains 22 ascii characters to describe 16 morphological characters because two of the morphological characters have polymorphism (ambiguity).

The error reported in BEAUti doesn't quite match this though:

java.lang.Exception: 		;
Expected sequence of length 16 instead of 29 for taxon 7
	at beast.util.NexusParser.parseDataBlock(NexusParser.java:469)
	at beast.util.NexusParser.parseFile(NexusParser.java:83)
	at beast.util.NexusParser.parseFile(NexusParser.java:58)
	at beast.app.beauti.BeautiAlignmentProvider.getAlignments(BeautiAlignmentProvider.java:99)
	at beast.app.beauti.BeautiAlignmentProvider.getAlignments(BeautiAlignmentProvider.java:76)
	at beast.app.beauti.Beauti$ActionImport.actionPerformed(Beauti.java:396)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)

**Comment by rbouckaert** [comment]
by a371e0b
