### ISSUE TITLE
NullPointerException thrown on running BEAST for Divergence time dating tutorial

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#262]
File: Primates.xml seed: 1422455329865 threads: 1
Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path
Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path
Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path
Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path
Start likelihood: -8749.328528062788 
java.lang.NullPointerException
    at beast.core.Logger.openLogFile(Unknown Source)
    at beast.core.Logger.init(Unknown Source)
    at beast.core.MCMC.run(Unknown Source)
    at beast.app.BeastMCMC.run(Unknown Source)
    at beast.app.beastapp.BeastMain.<init>(Unknown Source)
    at beast.app.beastapp.BeastMain.main(Unknown Source)
    at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Trying to write file /Users/m_matschiner/Desktop/primate-mtDNA.log but the file already exists (perhaps use the -overwrite flag?).
Overwrite (Y/N)?:

**Comment by rbouckaert** [comment]
By d0c3a0ca6846fe388c2aa741c991da85d3aaa002
