### ISSUE TITLE
DISSECT ERROR:  Attribute "originHeight" was already specified for element "input"

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#274]
BEAUti 2.2.0

Start Beauti
Choose StarBEAST template
Load 26.nex, 29.nex.
Taxon sets: guess using everything before last _
Priors: choose DISSECT for Tree.t:Species, expand this

Note that Origin height appears twice. This did not happen in 2.1.3.
File - Save as. This appears to work, the file name appears in the title, but it does not save a file. There are error messages like:

ERROR:  'Attribute "originHeight" was already specified for element "input".'
ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Attribute "originHeight" was already specified for element "input".'
javax.xml.transform.TransformerException: javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Attribute "originHeight" was already specified for element "input".
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(Unknown Source)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(Unknown Source)
    at beast.util.XMLProducer.cleanUpXML(Unknown Source)
    at beast.util.XMLProducer.toXML(Unknown Source)
    at beast.app.beauti.BeautiDoc.toXML(Unknown Source)
    at beast.app.beauti.BeautiDoc.save(Unknown Source)
    at beast.app.beauti.BeautiDoc.save(Unknown Source)
    at beast.app.beauti.Beauti.saveFile(Unknown Source)
    at beast.app.beauti.Beauti.saveAs(Unknown Source)
  [... lots more....]

Cheers, Graham

**Comment by walterxie** [comment]
Dear Graham,

It seems there is a duplicated attribute "originHeight" defined in DISSECT's BEAUti template, which makes BEAUti generates two originHeight='@DISSECToriginHeight.t:Species' in the XML as below. Then, the exception was thrown because the validation rule is violated. Could you please check your template, or email me the location of that file?    

            <input id='DISSECTSpeciesTreeDivergenceTimesPrior.t:Species' spec='dissect.BirthDeathCollapseModel' name='distribution' collapseHeight='3.0E-5' relativeDeathRate='@DISSECTrelativeDeathRate.t:Species' collapseWeight='@DISSECTcollapseWeight.t:Species' originHeight='@DISSECToriginHeight.t:Species' birthDiffRate='@DISSECTbirthRate.t:Species' originHeight='@DISSECToriginHeight.t:Species' tree='@Tree.t:Species'/>

Cheers,

Walter

**Comment by walterxie** [comment]
Dear Graham,

The problem is that BirthDeathCollapseModel uses the duplicated input originHeight with YuleModel which it is inherited from. This duplication makes BEAUti generate originHeight twice. I do not know your model, but from my experience, I suggest you remove originHeight input from BirthDeathCollapseModel and use the one inherited from YuleModel. This will solve the problem. 

Cheers,
Walter
