### ISSUE TITLE
Addon manager not working in 2.2.0?

### ISSUE THREAD

**Issue by metasoarous** [CompEvol/beast2#297]
I've used the addon manager from 2.1.2 successfully, and on upgrading to 2.2.0, I get the following error message when running the addonmanager (with any args):

    Exception in thread "main" java.lang.UnsupportedClassVersionError: beast/util/AddOnManager : Unsupported major.minor version 52.0
            at java.lang.ClassLoader.defineClass1(Native Method)
            at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
            at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
            at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
            at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
            at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by tgvaughan** [comment]
Hi @metasoarous , this is the kind of error you see when trying to run newer java programs on an older jvm.  Do you have Java 8 installed?  Is it accessible from the command line?  (What is the output of "java -version"?)

**Comment by metasoarous** [comment]
Ah; that's it then. Pretty sure I was running on 7.

Perhaps a clearer error message would be helpful?

**Comment by tgvaughan** [comment]
Good idea.  What you saw is java complaining though - it didn't even run any beast code there, so we have little control over that.  There are funky ways around this though (that I believe we have in place for beast itself) so hopefully we can wrangle things so that a friendlier error appears.

**Comment by metasoarous** [comment]
Ah; ok. Thanks for clearing things up.

**Comment by rbouckaert** [comment]
Should be fixed by #286.
