### ISSUE TITLE
How do I build and run beauti?

### ISSUE THREAD

**Issue by Anaphory** [CompEvol/beast2#298]
I have just cloned the current repository, and tried to build everything from source.
`ant` runs without complications, but does not build `beauti.jar`, and the target that looks like it is supposed to do that does not contain any reference to `beauti.jar`. How do I build and run beauti?

**Comment by tgvaughan** [comment]
Hi @Anaphory, beauti is packaged within beast.jar, which is built by the ant script.  Once the build is complete, run the following command from the root of the beast directory tree:

```sh
java -cp build/dist/beast.jar beast.app.beauti.Beauti
```

For hints at how this is done in the beast releases, look at the shell scripts in the `release/Linux/bin` directory.

**Comment by Anaphory** [comment]
Cool, that works. Thank you. However, I had looked inside `release/Linux/bin/beauti`, and it tries to find `beast.app.beauti.BeautiLauncher` in `launcher.jar`, which does not work.

    jardir = /home/gereon/grammarevolution/beast2/build/dist/launcher.jar
    Checking out /home/gereon/grammarevolution/beast2/build/dist/lib
    Checking out /home/gereon/grammarevolution/beast2/build/lib
    Checking out /home/gereon/grammarevolution/beast2/lib
    Loaded URL file:/home/gereon/grammarevolution/beast2/lib/beast.jar
    Exception in thread "main" java.lang.ClassNotFoundException: beast.evolution.alignment.Alignment
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:260)
        at beast.app.beastapp.BeastLauncher.loadBEASTJars(Unknown Source)
        at beast.app.beauti.BeautiLauncher.main(Unknown Source)

**Comment by Anaphory** [comment]
Anyway. Sorry that I had not realised that this does not say “Beauti not found” but instead says “Alignment not found”. I should have realised that and checked if that is a know issue. It is therefore not an issue with BEAUti as such, and should be separate for the purpose of finding it.

**Comment by tgvaughan** [comment]
Ah yes, the release scripts use some magic to ensure that user-friendly error messages appear when older JREs are used.  Sorry for the confusion, but glad you figured it out.
