### ISSUE TITLE
Alignment class not found when starting beauti from launcher

### ISSUE THREAD

**Issue by Anaphory** [CompEvol/beast2#299]
Having built beast from the current source code in the repository, I tried to start beauti according to `release/linux/beauti` as

    $ java -cp build/dist/launcher.jar -Djava.library.path=lib beast.app.beauti.BeautiLauncher                       

which results in 

    jardir = /home/gereon/grammarevolution/beast2/build/dist/launcher.jar
    Checking out /home/gereon/grammarevolution/beast2/build/dist/lib
    Checking out /home/gereon/grammarevolution/beast2/build/lib
    Checking out /home/gereon/grammarevolution/beast2/lib
    Loaded URL file:/home/gereon/grammarevolution/beast2/lib/beast.jar
    Exception in thread "main" java.lang.ClassNotFoundException: beast.evolution.alignment.Alignment
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:260)
        at beast.app.beastapp.BeastLauncher.loadBEASTJars(Unknown Source)
        at beast.app.beauti.BeautiLauncher.main(Unknown Source)

**Comment by rbouckaert** [comment]
Launcher loaded a file beast.jar from lib, so perhaps you can have a look whether it contains the missing class? You can also try to run BEAUti using

java -cp build beast.app.beauti.Beauti

**Comment by Anaphory** [comment]
Yes, `java -cp build beast.app.beauti.Beauti` works. I just don't know where I would have found that information without asking.

(tgvaughan mentioned a similar command it in another issue, but I thought anyone as unfamiliar with it as myself with the innards of beast might not find that issue when searching for a result, so I thought it might be a good idea to submit it as a separate issue. Close this if you consider everything said.)

**Comment by rbouckaert** [comment]
The launcher mechanism is there to check the JRE version, since we moved from Java 6 to Java 8 in the last release, and many users have not updated their JRE yet. 

So, there are now two ways to start BEAUti: through beast.app.beauti.BeautiLauncher and through beast.app.beauti.Beauti.

After checking version numbers, BeautiLauncher searches for beast.jar and loads it, then calls beast.app.beauti.Beauti. This is not very convenient for developers, since it means having to build the jar file every time, putting it in a place where the launcher probes, and it also hampers debugging. 

For developers, the recommended method is to use beast.app.beauti.Beauti directly instead of via the launcher.
