### ISSUE TITLE
BEAUti *BEAST RuntimeException after unlink tree given taxon set

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#416]
BEAUti *BEAST template:
1) Load 3 alginments, link trees;
2) Goto "Priors" or "Multi Species Coalescent", and add a taxon set;
3) Goto "Partitions", and unlink trees.

Processing: SpeciesTreeLoggerX -> 47
Input 101: type mismatch for input log. beast.core.Loggable.isAssignableFrom(class beast.evolution.alignment.Alignment)=false
java.lang.RuntimeException: Input 101: type mismatch for input log. beast.core.Loggable.isAssignableFrom(class beast.evolution.alignment.Alignment)=false
    at beast.core.Input.setValue(Unknown Source)
    at beast.core.BEASTInterface.setInputValue(Unknown Source)
    at beast.app.beauti.BeautiDoc.deepCopyPlugin(Unknown Source)
    at beast.app.beauti.AlignmentListInputEditor.updateModel(Unknown Source)
    at beast.app.beauti.AlignmentListInputEditor.unlink(Unknown Source)
    at beast.app.beauti.AlignmentListInputEditor.lambda$addLinkUnlinkPair$6(Unknown Source)
    at beast.app.beauti.AlignmentListInputEditor$$Lambda$9/398110318.actionPerformed(Unknown Source)
...

**Comment by rbouckaert** [comment]
I have not been able to reproduce this problem, so assume it was fixed by some commit in the mean time. Reopen if you think this is still a problem.
