### ISSUE TITLE
No resume with ' in ids

### ISSUE THREAD

**Issue by Anaphory** [CompEvol/beast2#657]
When reading a configuration file, beast accepts `'` as part of tag ids. When it stores a state, though, it writes the id as a `'`-delimited attribute of the tag, which makes the XML parser fail during a resume.

# Example
The `lexicon.xml` contains

    <siteModel id="SiteModel.lexicon:father's sister" mutationRate="@featureClockRate:lexicon:father's sister" proportionInvariant="0" shape="1" spec="SiteModel" substModel="@lexicon:covarion.s" />
and runs without problem. It writes a `lexicon.xml.state` with the line

    <statenode id='featureClockRate:lexicon:father's sister'>featureClockRate:lexicon:father's sister[1 1] (0.0,Infinity): 0.9246951496528801 </statenode>
so `beast -resume lexicon.xml` fails with

```
[Fatal Error] lessersunda_noproto_ratevariation_nonaustronesian_typology_autocode.xml.state:132:48: Element type "statenode" must be followed by either attribute specifications, ">" or "/>".
Fatal exception: Element type "statenode" must be followed by either attribute specifications, ">" or "/>".
org.xml.sax.SAXParseException; systemId: file:/home/gereon/analysis/basic/lessersunda_noproto_ratevariation_nonaustronesian_typology_autocode/lessersunda_noproto_ratevariation_nonaustronesian_typology_autocode.xml.state; lineNumber: 132; columnNumber: 48; Element type "statenode" must be followed by either attribute specifications, ">" or "/>".
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at beast.core.State.restoreFromFile(Unknown Source)
	at beast.core.MCMC.run(Unknown Source)
	at beast.app.BeastMCMC.run(Unknown Source)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Fatal exception: Element type "statenode" must be followed by either attribute specifications, ">" or "/>".
java.lang.RuntimeException: An error was encounted. Terminating BEAST
	at beast.app.util.ErrorLogHandler.publish(Unknown Source)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at java.util.logging.Logger.severe(Logger.java:1464)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)

```

**Comment by rbouckaert** [comment]
Looks like the ID does not go through the proper XML normalisation, so this is probably a problem with IDs containing other special characters as well (&, ", <, >).
