### ISSUE TITLE
Fatal exception: 4 apparently caused by "totalcount" <sequence> attribute on *BEAST 2

### ISSUE THREAD

**Issue by erico171** [CompEvol/beast2#684]
Hello everyone,

I'm running starbeast2 version 0.13.5 on openSUSE Leap 42.2 (64bits) with openjdk version "1.8.0_121". I'm using two different types of markers (cytb and many UCE loci) and I'm getting an error (pasted at the end of this post) just before the beginning of the mcmc. 
1. First I noticed that removing cytb everything worked just fine. Then, looking into the xml file, I observed that the attribute "totalcount" inside "sequence" tag was different for cytb (=20, while for the UCE loci it was =4). 
2. I found out that either making totalcount=4 for cytb or removing all "totalcount" attributes from the xml file solves the problem. For me it makes sense removig "totalcount", since at the BEAST v2.4.5 Documentation I saw that "totalcount" represents the "number of states or the number of lineages for this species in SNAPP analysis", and I'm not even using SNAPP, although I have it installed.

I also tested the xml generated as described above on a Windows 10 machine, it presents the same issue.

```
StarBEAST2: using fullInit to initialize all trees.
Fatal exception: 4
java.lang.ArrayIndexOutOfBoundsException: 4
        at beast.evolution.likelihood.BeerLikelihoodCore.calculateLogLikelihoods(Unknown Source)
        at beast.evolution.likelihood.TreeLikelihood.traverse(Unknown Source)
        at beast.evolution.likelihood.TreeLikelihood.calculateLogP(Unknown Source)
        at beast.core.util.CompoundDistribution.calculateLogP(Unknown Source)
        at beast.core.util.CompoundDistribution.calculateLogP(Unknown Source)
        at beast.core.State.robustlyCalcPosterior(Unknown Source)
        at beast.core.MCMC.run(Unknown Source)
        at beast.app.BeastMCMC.run(Unknown Source)
        at beast.app.beastapp.BeastMain.<init>(Unknown Source)
        at beast.app.beastapp.BeastMain.main(Unknown Source)
        at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Fatal exception: 4
java.lang.RuntimeException: An error was encounted. Terminating BEAST
        at beast.app.util.ErrorLogHandler.publish(Unknown Source)
        at java.util.logging.Logger.log(Logger.java:738)
        at java.util.logging.Logger.doLog(Logger.java:765)
        at java.util.logging.Logger.log(Logger.java:788)
        at java.util.logging.Logger.severe(Logger.java:1464)
        at beast.app.beastapp.BeastMain.<init>(Unknown Source)
        at beast.app.beastapp.BeastMain.main(Unknown Source)
        at beast.app.beastapp.BeastLauncher.main(Unknown Source)
```

**Comment by rbouckaert** [comment]
Thanks for the bug report. Is it possible that you imported fasta files and the alignments were guessed to be amino-acid, but you changed it to nucleotide? If so, I believe this is fixed by d471bf9590365e5b6e36f1c0ebd11f26f8ed59f0.

**Comment by tgvaughan** [comment]
I just stumbled upon this myself independently.  I can reproduce this problem by importing the attached fasta file (3 sequences, nucleotide with a single IUPAC ambiguity code R) into BEAUti.  A option dialog is displayed from which I select "nucleotide".  BEAUti then displays "nucleotode" as the datatype in the partition panel.  Saving the model and running the resulting XML produces the observed error.  Looking at the XML, the <sequence> elements have `totalcount="20"` set.  Removing this attribute fixes the problem.

Here's the test file: [test.fasta.txt](https://github.com/CompEvol/beast2/files/931591/test.fasta.txt) (Note github adds the txt extension.)

**Comment by tgvaughan** [comment]
And this is post d471bf9

**Comment by tgvaughan** [comment]
Woops, scratch that.  I was using the release version of BEAUti to construct the file, which still has the bug.  Using BEAUti from the current master branch does fix the issue.  This issue should probably be closed now.
