### ISSUE TITLE
BEAUTi on Linux cannot import morphological alignments

### ISSUE THREAD

**Issue by genomescale** [CompEvol/beast2#700]
BEAUTi will not import the example nexus file "traitlab.nex" or any other nexus file with morphological data. There will be no error if MM is not installed, but there will be a NULL error raised when MM is installed. Tested on my laptop and Tim's desktop. Walter's iMac is fine, so I'm guessing the issue is Linux specific.

**Comment by rbouckaert** [comment]
It may be dependent on the set of packages that is installed, not the OS.
What error do you get in the Help/Messages dialog?

**Comment by tgvaughan** [comment]
Here's what I see in the Messages dialog.  Interestingly, the problem only occurs the _first_ time I try to load the data.  A second attempt causes it to load just fine!

```
BeastMain found in /home/tvaughan/.beast/2.4/BEAST/lib/beast.jar
BeastMain found in /home/tvaughan/.beast/2.4/BEAST/lib/beast.jar
BeastMain found in /home/tvaughan/.beast/2.4/BEAST/lib/beast.jar
BeastMain found in /home/tvaughan/.beast/2.4/BEAST/lib/beast.jar
Loading package BEAST v2.4.6
Probing: beast.jar Skip loading file:/home/tvaughan/.beast/2.4/BEAST/lib/beast.jar: contains class beast.app.BEASTVersion that is already loaded
Loading package bacter v1.2.1
Probing: guava-17.0.jar Skip loading file:/home/tvaughan/.beast/2.4/bacter/lib/guava-17.0.jar: contains class com.google.common.annotations.Beta that is already loaded
Probing: feast.v4.2.0.jar Skip loading file:/home/tvaughan/.beast/2.4/bacter/lib/feast.v4.2.0.jar: contains class feast.expressions.ExpCalculator that is already loaded
Probing: bacter.v1.2.1.jar Skip loading file:/home/tvaughan/.beast/2.4/bacter/lib/bacter.v1.2.1.jar: contains class bacter.ACGEventList$Event that is already loaded
Loading package STACEY v1.2.2
Probing: stacey.jar Skip loading file:/home/tvaughan/.beast/2.4/STACEY/lib/stacey.jar: contains class stacey.BirthDeathCollapseModel that is already loaded
Loading package BEASTLabs v1.7.0
Probing: BEASTlabs.addon.jar Skip loading file:/home/tvaughan/.beast/2.4/BEASTLabs/lib/BEASTlabs.addon.jar: contains class beast.app.beast1to2.BEAST1SAXHandler that is already loaded
Loading package BASTA v2.2.1
Probing: BASTA.v2.2.1.jar Skip loading file:/home/tvaughan/.beast/2.4/BASTA/lib/BASTA.v2.2.1.jar: contains class beast.evolution.tree.MigrationModelVolz that is already loaded
Probing: jblas-1.2.3.jar Skip loading file:/home/tvaughan/.beast/2.4/BASTA/lib/jblas-1.2.3.jar: contains class org.jblas.DoubleMatrix that is already loaded
Probing: guava-15.0.jar Skip loading file:/home/tvaughan/.beast/2.4/BASTA/lib/guava-15.0.jar: contains class com.google.common.annotations.Beta that is already loaded
Loading package feast v4.2.0
Probing: feast.v4.2.0.jar Skip loading file:/home/tvaughan/.beast/2.4/feast/lib/feast.v4.2.0.jar: contains class feast.expressions.ExpCalculator that is already loaded
Loading package MASTER v5.1.1
Probing: jackson-core-2.2.3.jar Skip loading file:/home/tvaughan/.beast/2.4/MASTER/lib/jackson-core-2.2.3.jar: contains class com.fasterxml.jackson.core.base.GeneratorBase$1 that is already loaded
Probing: MASTER.package.v5.1.1.jar Skip loading file:/home/tvaughan/.beast/2.4/MASTER/lib/MASTER.package.v5.1.1.jar: contains class master.BeastTreeFromMaster that is already loaded
Probing: jackson-annotations-2.2.3.jar Skip loading file:/home/tvaughan/.beast/2.4/MASTER/lib/jackson-annotations-2.2.3.jar: contains class com.fasterxml.jackson.annotation.JacksonAnnotation that is already loaded
Probing: jackson-databind-2.2.3.jar Skip loading file:/home/tvaughan/.beast/2.4/MASTER/lib/jackson-databind-2.2.3.jar: contains class com.fasterxml.jackson.databind.AbstractTypeResolver that is already loaded
Probing: guava-16.0.1.jar Skip loading file:/home/tvaughan/.beast/2.4/MASTER/lib/guava-16.0.1.jar: contains class com.google.common.annotations.Beta that is already loaded
Loading package MultiTypeTree v7.0.0-pre
Probing: MultiTypeTree.v7.0.0-pre.jar Skip loading file:/home/tvaughan/.beast/2.4/MultiTypeTree/lib/MultiTypeTree.v7.0.0-pre.jar: contains class beast.app.multitypetree.beauti.InitMigrationModelConnector that is already loaded
Probing: jblas-1.2.3.jar Skip loading file:/home/tvaughan/.beast/2.4/MultiTypeTree/lib/jblas-1.2.3.jar: contains class org.jblas.DoubleMatrix that is already loaded
Probing: guava-15.0.jar Skip loading file:/home/tvaughan/.beast/2.4/MultiTypeTree/lib/guava-15.0.jar: contains class com.google.common.annotations.Beta that is already loaded
Loading package BEAST v2.4.6
Probing: beast.jar Skip loading file:/home/tvaughan/.beast/2.4/BEAST/lib/beast.jar: contains class beast.app.BEASTVersion that is already loaded
Loading package substBMA v1.2.2
Probing: substBMA.v1.2.2.jar Skip loading file:/home/tvaughan/.beast/2.4/substBMA/lib/substBMA.v1.2.2.jar: contains class beast.core.MCMCNodeFactory that is already loaded
Probing: colt.jar Skip loading file:/home/tvaughan/.beast/2.4/substBMA/lib/colt.jar: contains class cern.clhep.PhysicalConstants that is already loaded
Loading package bModelTest v1.0.3
Probing: bModelTest.addon.jar Skip loading file:/home/tvaughan/.beast/2.4/bModelTest/lib/bModelTest.addon.jar: contains class beast.app.beauti.BEASTModelTestInputEditor that is already loaded
Loading package BDSKY v1.3.3
Probing: BDSSM.addon.jar Skip loading file:/home/tvaughan/.beast/2.4/BDSKY/lib/BDSSM.addon.jar: contains class beast.evolution.speciation.BirthDeathSkylineModel$1 that is already loaded
Loading package SA v1.1.7
Probing: SA.addon.jar Skip loading file:/home/tvaughan/.beast/2.4/SA/lib/SA.addon.jar: contains class beast.app.simulators.SABDSimulator$1 that is already loaded
Loading template /home/tvaughan/.beast/2.4/BEAST/templates/Standard.xml
Investigating /home/tvaughan/.beast/2.4/BDSKY
Processing /home/tvaughan/.beast/2.4/BDSKY/templates/BDSKY_contemp.xml
Processing /home/tvaughan/.beast/2.4/BDSKY/templates/BDSKY_serial.xml
Processing /home/tvaughan/.beast/2.4/BDSKY/templates/SAFBDSKY.xml
Processing /home/tvaughan/.beast/2.4/BDSKY/templates/BDSKY_multiRho.xml
Processing /home/tvaughan/.beast/2.4/BDSKY/templates/SABDSKY.xml
Investigating /home/tvaughan/.beast/2.4/BEAST
Processing /home/tvaughan/.beast/2.4/BEAST/templates/ParametricDistributions.xml
Processing /home/tvaughan/.beast/2.4/BEAST/templates/ClockModels.xml
Processing /home/tvaughan/.beast/2.4/BEAST/templates/TreePriors.xml
Processing /home/tvaughan/.beast/2.4/BEAST/templates/StarBeast.xml
Processing /home/tvaughan/.beast/2.4/BEAST/templates/SubstModels.xml
Investigating /home/tvaughan/.beast/2.4/STACEY
Processing /home/tvaughan/.beast/2.4/STACEY/templates/StarBeastWithSTACEYops.xml
Processing /home/tvaughan/.beast/2.4/STACEY/templates/STACEY.xml
Investigating /home/tvaughan/.beast/2.4/BEASTLabs
Investigating /home/tvaughan/.beast/2.4/BASTA
Processing /home/tvaughan/.beast/2.4/BASTA/templates/BASTAClockModels.xml
Cannot find merge point named BASTAClockModelTemplates from BASTAClockModels.xml in template. MergeWith ignored.
Processing /home/tvaughan/.beast/2.4/BASTA/templates/BASTA.xml
Investigating /home/tvaughan/.beast/2.4/bacter
Processing /home/tvaughan/.beast/2.4/bacter/templates/BacterACGPriors.xml
Cannot find merge point named ACGPriorTemplates from BacterACGPriors.xml in template. MergeWith ignored.
Processing /home/tvaughan/.beast/2.4/bacter/templates/Bacter.xml
Investigating /usr/local/lib/BEAST
Processing /usr/local/lib/BEAST/templates/Standard.xml
Skipping /usr/local/lib/BEAST/templates/ParametricDistributions.xml since ParametricDistributions.xml is already processed
Skipping /usr/local/lib/BEAST/templates/ClockModels.xml since ClockModels.xml is already processed
Skipping /usr/local/lib/BEAST/templates/TreePriors.xml since TreePriors.xml is already processed
Skipping /usr/local/lib/BEAST/templates/StarBeast.xml since StarBeast.xml is already processed
Skipping /usr/local/lib/BEAST/templates/SubstModels.xml since SubstModels.xml is already processed
Investigating /home/tvaughan/.beast/2.4/MASTER
Investigating .
Investigating /home/tvaughan/.beast/2.4/bModelTest
Processing /home/tvaughan/.beast/2.4/bModelTest/templates/bModelTest.xml
Investigating /home/tvaughan/.beast/2.4/SA
Processing /home/tvaughan/.beast/2.4/SA/templates/FBD.xml
Investigating /home/tvaughan/.beast/2.4/substBMA
Processing /home/tvaughan/.beast/2.4/substBMA/templates/wishartDistribution.xml
Processing /home/tvaughan/.beast/2.4/substBMA/templates/substBMA.xml
Investigating /home/tvaughan/.beast/2.4/MultiTypeTree
Processing /home/tvaughan/.beast/2.4/MultiTypeTree/templates/MultiTypeTree.xml
Processing /home/tvaughan/.beast/2.4/MultiTypeTree/templates/MTTClockModels.xml
Cannot find merge point named mttClockModelTemplates from MTTClockModels.xml in template. MergeWith ignored.
connect => beast.app.beauti.BeautiConnector
subtemplate => beast.app.beauti.BeautiSubTemplate
Uniform => beast.math.distributions.Uniform
Normal => beast.math.distributions.Normal
OneOnX => beast.math.distributions.OneOnX
LogNormal => beast.math.distributions.LogNormalDistributionModel
Exponential => beast.math.distributions.Exponential
Gamma => beast.math.distributions.Gamma
Beta => beast.math.distributions.Beta
LaplaceDistribution => beast.math.distributions.LaplaceDistribution
InverseGamma => beast.math.distributions.InverseGamma
prior => beast.math.distributions.Prior
map
map
map
map
map
map
map
map
map
map
map
map
beauticonfig
fragment
run
===============================================================================
Citations for this model:

Bouckaert RR, Heled J, Kuehnert D, Vaughan TG, Wu C-H, Xie D, Suchard MA,
  Rambaut A, Drummond AJ (2014) BEAST 2: A software platform for Bayesian
  evolutionary analysis. PLoS Computational Biology 10(4): e1003537

===============================================================================
Warning: at least one operator required to run the MCMC properly, but none found.
template item TreeOperators is ignored
PARTITIONS0:

[[], [], []]
InPosterior=posterior prior likelihood 
Could not find beastObject with id treeLikelihood.Species. Typo in template perhaps?

Validation message: At least one input of name 'xx' must be specified.
class beast.core.MCMC != class beast.core.Runnable
PARTITIONS0:

[[], [], []]
BeastMain found in /home/tvaughan/.beast/2.4/BEAST/lib/beast.jar
BeastMain found in /home/tvaughan/.beast/2.4/BEAST/lib/beast.jar
BeastMain found in /home/tvaughan/.beast/2.4/BEAST/lib/beast.jar
BeastMain found in /home/tvaughan/.beast/2.4/BEAST/lib/beast.jar
Warning: expected datatype (e.g. something like 'format datatype=dna;') not 'FORMAT MISSING=? GAP=- INTERLEAVE  ' Assuming integer dataType
taxon_1: 30 4
taxon_2: 30 4
taxon_3: 30 4
taxon_4: 30 4
taxon_5: 30 4
taxon_6: 30 4
taxon_7: 30 4
taxon_8: 30 4
taxon_9: 30 4
Alignment(null)
  9 taxa
  30 sites
  24 patterns

plugin
beast.evolution.sitemodel.SiteModel.substModel: java.lang.ClassCastException: beast.evolution.sitemodel.BEASTModelTestSiteModel cannot be cast to beast.evolution.substitutionmodel.SubstitutionModel
beast.evolution.sitemodel.SiteModel.substModel: java.lang.ClassCastException: beast.evolution.sitemodel.SiteModel cannot be cast to beast.evolution.substitutionmodel.SubstitutionModel
plugin
Adding beast.evolution.substitutionmodel.JukesCantor JC69.s:traitlab
plugin
prior
prior
taxonset
plugin
plugin
plugin
plugin
logger
operator
operator
operator
operator
operator
operator
operator
operator
operator
operator
operator
prior
prior
prior
operator
operator
upDownOperator
Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path
TreeLikelihood(treeLikelihood.traitlab0) uses BeerLikelihoodCore4
  Alignment(traitlab): [taxa, patterns, sites] = [9, 24, 30]
java.lang.NullPointerException
	at beast.evolution.datatype.DataType$Base.getStatesForCode(Unknown Source)
	at beast.evolution.likelihood.TreeLikelihood.setStates(Unknown Source)
	at beast.evolution.likelihood.TreeLikelihood.setStates(Unknown Source)
	at beast.evolution.likelihood.TreeLikelihood.setStates(Unknown Source)
	at beast.evolution.likelihood.TreeLikelihood.setStates(Unknown Source)
	at beast.evolution.likelihood.TreeLikelihood.setStates(Unknown Source)
	at beast.evolution.likelihood.TreeLikelihood.setStates(Unknown Source)
	at beast.evolution.likelihood.TreeLikelihood.setStates(Unknown Source)
	at beast.evolution.likelihood.TreeLikelihood.setStates(Unknown Source)
	at beast.evolution.likelihood.TreeLikelihood.setStates(Unknown Source)
	at beast.evolution.likelihood.TreeLikelihood.initCore(Unknown Source)
	at beast.evolution.likelihood.TreeLikelihood.initAndValidate(Unknown Source)
	at beast.core.BEASTInterface.initByName(Unknown Source)
	at beast.evolution.likelihood.ThreadedTreeLikelihood.initAndValidate(Unknown Source)
	at beast.util.XMLParser.initBEASTObjects(Unknown Source)
	at beast.util.XMLParser.parseTemplate(Unknown Source)
	at beast.app.beauti.BeautiSubTemplate.createSubNet(Unknown Source)
	at beast.app.beauti.BeautiSubTemplate.createSubNet(Unknown Source)
	at beast.app.beauti.BeautiDoc.addAlignmentWithSubnet(Unknown Source)
	at beast.app.beauti.BeautiAlignmentProvider.addAlignments(Unknown Source)
	at beast.app.beauti.BeautiAlignmentProvider.getAlignments(Unknown Source)
	at beast.app.beauti.BeautiAlignmentProvider.getAlignments(Unknown Source)
	at beast.app.beauti.Beauti$1.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicPopupMenuUI$Actions.doReturn(BasicPopupMenuUI.java:455)
	at javax.swing.plaf.basic.BasicPopupMenuUI$Actions.actionPerformed(BasicPopupMenuUI.java:429)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:250)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6310)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.RuntimeException: initAndValidate() failed! null
	at beast.core.BEASTInterface.initByName(Unknown Source)
	at beast.evolution.likelihood.ThreadedTreeLikelihood.initAndValidate(Unknown Source)
	at beast.util.XMLParser.initBEASTObjects(Unknown Source)
	at beast.util.XMLParser.parseTemplate(Unknown Source)
	at beast.app.beauti.BeautiSubTemplate.createSubNet(Unknown Source)
	at beast.app.beauti.BeautiSubTemplate.createSubNet(Unknown Source)
	at beast.app.beauti.BeautiDoc.addAlignmentWithSubnet(Unknown Source)
	at beast.app.beauti.BeautiAlignmentProvider.addAlignments(Unknown Source)
	at beast.app.beauti.BeautiAlignmentProvider.getAlignments(Unknown Source)
	at beast.app.beauti.BeautiAlignmentProvider.getAlignments(Unknown Source)
	at beast.app.beauti.Beauti$1.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicPopupMenuUI$Actions.doReturn(BasicPopupMenuUI.java:455)
	at javax.swing.plaf.basic.BasicPopupMenuUI$Actions.actionPerformed(BasicPopupMenuUI.java:429)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:250)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6310)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
beast.util.XMLParserException: 
Error 110 parsing the xml input file

validate and intialize error: initAndValidate() failed! null

Error detected about here:
  <beast>
      <plugin id='treeLikelihood.traitlab' spec='ThreadedTreeLikelihood'>

	at beast.util.XMLParser.initBEASTObjects(Unknown Source)
	at beast.util.XMLParser.parseTemplate(Unknown Source)
	at beast.app.beauti.BeautiSubTemplate.createSubNet(Unknown Source)
	at beast.app.beauti.BeautiSubTemplate.createSubNet(Unknown Source)
	at beast.app.beauti.BeautiDoc.addAlignmentWithSubnet(Unknown Source)
	at beast.app.beauti.BeautiAlignmentProvider.addAlignments(Unknown Source)
	at beast.app.beauti.BeautiAlignmentProvider.getAlignments(Unknown Source)
	at beast.app.beauti.BeautiAlignmentProvider.getAlignments(Unknown Source)
	at beast.app.beauti.Beauti$1.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicPopupMenuUI$Actions.doReturn(BasicPopupMenuUI.java:455)
	at javax.swing.plaf.basic.BasicPopupMenuUI$Actions.actionPerformed(BasicPopupMenuUI.java:429)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:250)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6310)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
PARTITIONS0:

[[], [], []]
InPosterior=posterior prior likelihood 
Could not find beastObject with id treeLikelihood.Species. Typo in template perhaps?

PARTITIONS0:

[[], [], []]
PARTITIONS0:

[[], [], []]
PARTITIONS0:

[[], [], []]
PARTITIONS0:

[[], [], []]
Validation message: At least one input of name 'xx' must be specified.
PARTITIONS0:

[[], [], []]
class beast.core.MCMC != class beast.core.Runnable
PARTITIONS0:

[[], [], []]
Validation message: At least one input of name 'xx' must be specified.
class beast.core.MCMC != class beast.core.Runnable
```

**Comment by genomescale** [comment]
I've tried it on BEAST 2.4.0, 2.4.5 and 2.4.6 release versions without any other packages installed with the same result

**Comment by rbouckaert** [comment]
Looks like the NexusParser assigns nucleotide as default datatype, since the datatype is not specified in the nexus file. Since the sequence only contains 0s and 1s, the datatype does not know what to make of these characters and throws exceptions when trying to translate them from code to state. The NexusParser could smarten up a bit and look at the sequence before deciding on the datatype.

**Comment by alexeid** [comment]
Let’s please not make the nexus parser do things that MrBayes or PAUP* don’t do. Those programs basically define standard expectations on behaviour, especially for reading in the data matrix.

Isn’t the correct response to this bug is to provide a better error to the user? Ideally a simple message in a pop-up dialog that says “no data type specified in the Nexus file”. 

If we don’t have a generally Exception-driven error handler in BEAUti then perhaps the response to this bug should be to add one. It would be nice to have a dedicated Exception subclass for parsing errors (NexusParserException extends Exception {} or NexusParserException extends RuntimeException {} depending on how backwards compatible you want to be), so that these particular class of exceptions could be recognized and caught by BEAuti, and reported to the user, so at the least the user knows that parsing failed, hopefully with a semi-sensible message that points them in the direction of why...

**Comment by genomescale** [comment]
I can't import alignments with the data type specified as "standard" either, so I'm not sure this is the root cause
