### ISSUE TITLE
Beauti out of heap memory loading an alignment

### ISSUE THREAD

**Issue by rafarios50** [CompEvol/beast2#714]
Greetings,

I'm having this error while trying to load an alignment in nexus format to beauti.
`Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:261)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
        at java.util.ArrayList.add(ArrayList.java:458)
        at beast.evolution.datatype.DataType$Base.string2state(Unknown Source)
        at beast.evolution.alignment.Sequence.getSequence(Unknown Source)
        at beast.evolution.alignment.Alignment.initializeWithSequenceList(Unknown Source)
        at beast.evolution.alignment.Alignment.initAndValidate(Unknown Source)
        at beast.util.NexusParser.parseDataBlock(Unknown Source)
        at beast.util.NexusParser.parseFile(Unknown Source)
        at beast.util.NexusParser.parseFile(Unknown Source)
        at beast.app.beauti.BeautiAlignmentProvider.getAlignments(Unknown Source)
        at beast.app.beauti.BeautiAlignmentProvider.getAlignments(Unknown Source)
        at beast.app.beauti.Beauti$1.actionPerformed(Unknown Source)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.Component.processMouseEvent(Component.java:6533)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6298)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)`

The alignment has 165 taxa and 3508587 characters, all of them nucleotides.

Is there a way to increase the heap memory size for beauti or where I could find the .jar for beauti and set the Xmx directly?

Thank you

**Comment by SimonGreenhill** [comment]
https://www.beast2.org/increasing-memory-usage/

**Comment by rafarios50** [comment]
Thanks for the link, but unfortunately it doesn't work for me because the solution is for BEAST and not for beauti, which is the one sending the Java heap space error.

**Comment by SimonGreenhill** [comment]
Do the same thing, just with the BEAUTi app.

**Comment by rafarios50** [comment]
But where do I find the jar for beauti, I only have the executable and could not find the .jar

My installation folder looks like this:

/source_installers/BEASTv2.4.2/beast/LICENSE.txt
/source_installers/BEASTv2.4.2/beast/VERSION HISTORY.txt
/source_installers/BEASTv2.4.2/beast/README.txt

/source_installers/BEASTv2.4.2/beast/bin:
addonmanager  appstore  beast  beauti  densitree  loganalyser  logcombiner  treeannotator

/source_installers/BEASTv2.4.2/beast/examples:
bitflip.xml                              testJukesCantorShortUncertain2.xml          testSRD06.xml
nexus                                    testJukesCantorShortUncertain.xml           testStarBeast.xml
testBSP.xml                              testJukesCantorShort.xml                    testSYM.xml
testCalibration.xml                      testJukesCantor.xml                         testTIM.xml
testCalYule_5t_2c.xml                    testMultipleAlignments_randomTaxaOrder.xml  testTipDates2.xml
testClassicRootCalibrationPrior.xml      testPlates.xml                              testTipDates.xml
testCoalescent.xml                       testRandomLocalClock.xml                    testTN93.xml
testConditionalRootCalibrationPrior.xml  testRelaxedClock.xml                        testTVM.xml
testEBSP.xml                             testRestrictedGTR.xml                       testTwoCalibrationsPrior.xml
testExponentialGrowth.xml                testRNA.xml                                 testYuleCalibrated.xml
testGTR.xml                              testSeqGen.xml                              testYuleOneSite.xml
testHKY.xml                              testSimulatedAlignment.xml                  testYuleUncalibrated.xml
testJukesCantorShortUncertain2MLE.xml    testSliceHKY.xml

/source_installers/BEASTv2.4.2/beast/images:
beast.png  beauti.png  DensiTree.png

/source_installers/BEASTv2.4.2/beast/lib:
beast.jar  beast.src.jar  DensiTree.jar  launcher.jar

/source_installers/BEASTv2.4.2/beast/templates:
ClockModels.xml  ParametricDistributions.xml  Standard.xml  StarBeast.xml  SubstModels.xml  TreePriors.xml


And in the lib directory there is only the .jar for beast

**Comment by SimonGreenhill** [comment]
Edit the file `/source_installers/BEASTv2.4.2/beast/bin/beauti` to change the -Xms and -Xmx parameters, e.g.:

```
$JAVA -Xms256m -Xmx4g -Djava.library.path="$BEAST_LIB" -cp "$BEAST_LIB/launcher.jar" beast.app.beauti.BeautiLauncher -capture $*
```

**Comment by zeawoas** [comment]
Whenever BEAST or one of the utility programs is run from their bin files the first line printed to STDOUT shows which JVM is used, library paths etc. For me this always starts with
`[/usr/lib/jvm/java-8-oracle/bin/java, -Xms8g, -Xms256m ...` regardless of what I specify in the corresponding bin file (i.e. the -Xms values never change). 

I also can't escape the heap space error with beauti, no matter how high of a -Xmx I use in the bin file. This makes me wonder if the jars are called in some other way from the app (I don't know anything about java, so please bear with me).

**Comment by rbouckaert** [comment]
@zeawoas the latest version (v2.5.2) should take -Xmx etc as argument to the scripts in the bin folder. So, you should be able to start BEAUti with

    /path/to/beast/bin/beauti -Xmx16g

(where "/path/to/beast/" is the path to where the BEAST program is), and STDOUT should print that it is using 16G byte instead of the default 8G byte. Can you make sure you are using v2.5.2?

By the way, this will change in version v2.6.0 (which should be available in a few weeks and is being tested right now), which does not launch a new process any more, unlike v2.5.x. In v2.6.0 you have to pass the -Xmx and other directives directly to java, so either modify the script in the bin directory, or from the command line call the launcher with the correct class name for the application, like so

    java -Xmx16g -cp /path/to/beast/lib/launcher.jar beast.app.beauti.Beauti

**Comment by zeawoas** [comment]
@rbouckaert Perfect, thanks!

**Comment by earnest-maelstrom7** [comment]
i’ve got it—the answer!



https://stackdev.space/questions/java-the-memory-has-run-out-error
