### ISSUE TITLE
*beast2RLC: Fatal exception based on incomplete taxon representation

### ISSUE THREAD

**Issue by hydrahamster** [CompEvol/beast2#715]
Hi there,

I'm trying to run *beast2RLC with 60 odd gene trees and up to 24 taxa. Looks like the problem is that not all taxa are represented in every gene alignment.

Test dataset with *beast2 RLC template worked fine previously, at that point taxa were represented in all gene alignments. Ran on Linux based cluster as well as Ubuntu OS laptop - this error is coming up for both systems now.

Is there a way to make this run without screening which taxa are missing in each gene alignment and then adding gaps? Thanks!

StarBEAST2: using fullInit to initialize all trees.
Fatal exception: Gene tree Tree.t:EPrGT00050000005290 has no lineages for species taxon ALEXANDRIUM-CATENELLA 
java.lang.RuntimeException: Gene tree Tree.t:EPrGT00050000005290 has no lineages for species taxon ALEXANDRIUM-CATENELLA 
	at starbeast2.StarBeastInitializer.fullInit(StarBeastInitializer.java:246)
	at starbeast2.StarBeastInitializer.initStateNodes(StarBeastInitializer.java:101)
	at beast.core.MCMC.run(Unknown Source)
	at beast.app.BeastMCMC.run(Unknown Source)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Fatal exception: Gene tree Tree.t:EPrGT00050000005290 has no lineages for species taxon ALEXANDRIUM-CATENELLA 
java.lang.RuntimeException: An error was encounted. Terminating BEAST
	at beast.app.util.ErrorLogHandler.publish(Unknown Source)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at java.util.logging.Logger.severe(Logger.java:1464)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)

**Comment by rbouckaert** [comment]
This was submitted as a BEAST 2 issue, but I think this is a SartBEAST2 issue, so transferred it as issue [#16](https://github.com/genomescale/starbeast2/issues/16) in the StartBEAST2 repo.
