### ISSUE TITLE
Error summarizing MrBayes trees using TreeAnnotator

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#737]
From the mailing list:
 
    I am trying to summarize 2000 trees from MrBayes in TreeAnnotator. I do it usually..
    Some new mistake:
    java.lang.NegativeArraySizeException
         at beast.app.treeannotator.TreeAnnotator$FastTreeSet.<init>(Unknown Source)
         at beast.app.treeannotator.TreeAnnotator.<init>(Unknown Source)
         at beast.app.treeannotator.TreeAnnotator.main(Unknown Source)
         at beast.app.treeannotator.TreeAnnotatorLauncher.main(Unknown Source)
    Error Parsing Input Tree: null

and then

    I realised that the only difference between my previous successful attempts and this
    one was the version of the TreeAnnotator. I downloaded version 2.3.2 and voilà! it
    works. So, it looks like version 2.4 lacked possibility of work with MrBayes. Is it possible
    to fix this problem?

This sounds like a regression.

**Comment by tgvaughan** [comment]
This is a nexus parser issue very similar to #146: the NexusParser class assumes that newlines have semantic value, when in fact alll whitespace is equal in nexus.
