### ISSUE TITLE
confusing error if no operator matches "operatorPattern" in "subschedule"

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#759]
@rbouckaert @alexeid 
If there is no operator matches "operatorPattern" in "subschedule", then it will throw index out of bound exception, which is confusing and misleading.

java.lang.IndexOutOfBoundsException: Index: 7, Size: 7
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at beast.core.OperatorSchedule.selectOperator(OperatorSchedule.java:181)
	at beast.core.MCMC.propagateState(MCMC.java:458)
...

```Java
             final int operatorIndex = Randomizer.randomChoice(cumulativeProbs);
 line181     return operators.get(operatorIndex);
```

**Comment by walterxie** [comment]
Add IllegalArgumentException to stop if no match. 

```Java
    protected void addOperators(Collection<Operator> ops) {
    	if (operatorPatternInput.get() == null || operatorPatternInput.get().trim().equals("")) {
    		return;
    	}
		String operatorPattern = operatorPatternInput.get();
    	boolean noMatch = true;
		for (Operator o : ops) {
			if (o.getID() != null && o.getID().matches(operatorPattern)) {
		    	for (Operator o2 : operators) {
		    		if (o2 == o) {
		    			// operator was already added earlier
		    			return;
		    		}
		    	}
				operators.add(o);
                noMatch = false;
			}
		}
    	reweighted = false;

		if (noMatch)
		   throw new IllegalArgumentException("Cannot find operator to match subschedule pattern: " + operatorPattern + " !\n");
    }
```

**Comment by rbouckaert** [comment]
Related to #28.
