### ISSUE TITLE
Resuming issue because of integer upper limit

### ISSUE THREAD

**Issue by walterxie** [CompEvol/beast2#767]
@rbouckaert 
The state “integer” type problem looks still existing when I tried to resume from the number more than the integer upper limit. The error message is:
 
Fatal exception: For input string: "2500000000"

java.lang.NumberFormatException: For input string: "2500000000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at beast.core.Logger.openLogFile(Logger.java:421)
	at beast.core.Logger.init(Logger.java:225)
	at beast.core.MCMC.run(MCMC.java:351)
	at beast.app.BeastMCMC.run(BeastMCMC.java:368)

To replicate error:
[log.zip](https://github.com/CompEvol/beast2/files/1874236/log.zip)

**Comment by rbouckaert** [comment]
No spurious instances of `Integer.parseInt(...)` found.
Logcombiner seems to work without problems on large log files as well.
