### ISSUE TITLE
BEAUti multi screen Linux problem

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#808]
This is on a laptop, with 2 external screens. BEAUti opens by default on external screen 1, but when you start Beauti and you try to  "File >" you get an exception (and no menu appearing) -- see stack below. Moving BEAUti to the laptop screen or external screen 2 and menus work without problem.

Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Window must not be zero
    at java.desktop/sun.awt.X11.XAtom.checkWindow(XAtom.java:774)
    at java.desktop/sun.awt.X11.XAtom.getAtomData(XAtom.java:465)
    at java.desktop/sun.awt.X11.XToolkit.getWorkArea(XToolkit.java:805)
    at java.desktop/sun.awt.X11.XToolkit.getInsets(XToolkit.java:881)
    at java.desktop/sun.awt.X11.XToolkit.getScreenInsets(XToolkit.java:869)
    at java.desktop/javax.swing.JMenu.getPopupMenuOrigin(JMenu.java:385)
    at java.desktop/javax.swing.JMenu.setPopupMenuVisible(JMenu.java:327)
    at java.desktop/javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1486)
    at java.desktop/javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:129)
    at java.desktop/javax.swing.plaf.basic.BasicMenuUI.appendPath(BasicMenuUI.java:258)
    at java.desktop/javax.swing.plaf.basic.BasicMenuUI.access$200(BasicMenuUI.java:49)
    at java.desktop/javax.swing.plaf.basic.BasicMenuUI$Handler.mousePressed(BasicMenuUI.java:519)
    at java.desktop/java.awt.Component.processMouseEvent(Component.java:6586)
    at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
    at java.desktop/java.awt.Component.processEvent(Component.java:6354)
    at java.desktop/java.awt.Container.processEvent(Container.java:2261)
    at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
    at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
    at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
    at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4914)
    at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4540)
    at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4484)
    at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2305)
    at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
    at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
    at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by tgvaughan** [comment]
Looks like it could be related to [this](https://bugs.openjdk.java.net/browse/JDK-8204646).

**Comment by rbouckaert** [comment]
@tgvaughan that is indeed the problem: it was with java "10.0.1 2018-04-17". From the link:

CUSTOMER SUBMITTED WORKAROUND :
Run the application on Java 8.
