### ISSUE TITLE
NullPointerException with ThreadedTreeLikelihood

### ISSUE THREAD

**Issue by J-Moravec** [CompEvol/beast2#865]
I am trying to parallelize BEAST. When threads and instances with and without beagle does not have the required effect, but I have found that ThreadedTreeLikelihood should do the trick (combined with these parameters).

However, when `ThreadedTreeLikelihood` is combined either with `-instances` or `-threads`, I get NullPointerException:

```
Fatal exception: null
java.lang.NullPointerException
	at beast.evolution.likelihood.ThreadedTreeLikelihood.requiresRecalculation(Unknown Source)
	at beast.core.CalculationNode.checkDirtiness(Unknown Source)
	at beast.core.State.checkCalculationNodesDirtiness(Unknown Source)
	at beast.core.State.robustlyCalcPosterior(Unknown Source)
	at beast.core.MCMC.run(Unknown Source)
	at beast.app.BeastMCMC.run(Unknown Source)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
Fatal exception: null
java.lang.RuntimeException: An error was encounted. Terminating BEAST
	at beast.app.util.ErrorLogHandler.publish(Unknown Source)
	at java.logging/java.util.logging.Logger.log(Logger.java:979)
	at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
	at java.logging/java.util.logging.Logger.log(Logger.java:1029)
	at java.logging/java.util.logging.Logger.severe(Logger.java:1776)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
```

MRE:

[mre.txt](https://github.com/CompEvol/beast2/files/3394588/mre.txt)

Linux and beast 2.6.0 with openjdk 11.0.3 2019-04-16 with packages Babel and BEASTLabs.

**Comment by rbouckaert** [comment]
Hi Jirka, 

Unfortunately, the threaded tree-likelihood cannot deal with ascertained data. Earlier in the log, you should have seen this message `Note, can only use single thread per alignment because the alignment is ascertained`. A workaround is to manually add multiple TreeLikelihoods that filter parts of the alignment, each with their own ascertainment correction.

Cheers, Remco

**Comment by J-Moravec** [comment]
Ah, thanks, never noticed this option before.

Is there anywhere I can read more about it? All I can get is this:

https://www.beast2.org/xml/beast.evolution.alignment.Alignment.html#ascertained

which isn't particularly revealing.

**Comment by rbouckaert** [comment]
I composed a post on this, which you can find [here](http://www.beast2.org/2019/07/18/ascertainment-correction.html). Let me know if anything remains unclear.
