### ISSUE TITLE
BEAST2 complains java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by senbaikang** [CompEvol/beast2#940]
Recently I have been encountering such errors that the programme cannot run at all. It appears both on macos under 10.15.7 as well as 11.0.1 and on ubuntu 20.04, with java8, 11, and 15. The beast versions I have tested are 2.6.0, 2.6.2, and 2.6.3, and I have no idea why this error happens. Here is the error message:

java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at beast.app.beastapp.BeastLauncher.run(Unknown Source)
        at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.apache.commons.math.distribution.ContinuousDistribution.logDensity(D)D
        at beast.math.distributions.ParametricDistribution.logDensity(Unknown Source)
        at beast.math.distributions.ParametricDistribution.calcLogP(Unknown Source)
        at beast.math.distributions.Prior.calculateLogP(Unknown Source)
        at beast.math.distributions.Prior.initAndValidate(Unknown Source)
        at beast.util.XMLParser.initBEASTObjects(Unknown Source)
        at beast.util.XMLParser.parse(Unknown Source)
        at beast.util.XMLParser.parseFile(Unknown Source)
        at beast.app.BeastMCMC.parseArgs(Unknown Source)
        at beast.app.beastapp.BeastMain.main(Unknown Source)
        ... 6 more

**Comment by inspirewind** [comment]
hello, I also encountered the same problem, how did you solve it?

**Comment by zyy-1111** [comment]
> hello, I also encountered the same problem, how did you solve it?

DID you solve it? I also encountered the same problem.
