### ISSUE TITLE
BUG: TipDateRandomWalker can lead to negative branch lengths

### ISSUE THREAD

**Issue by brj1** [CompEvol/beast2#995]
Using the TipDateRandomWalker with time forward dates and allowing the sampled tips to date later than the latest fixed tip date (height = 0) can result in a tree with negative branch lengths and subsequently crashes BEAST.

I have a small minimal example that illustrates this:  <[ex.zip](https://github.com/CompEvol/beast2/files/7023537/ex.zip)>. I get the following error after a a little more than 1000 iterations with BEAST v2.6.6 with no packages using the random seed 1629484802442.

```
Fatal exception: Negative branch length: -0.1985531009935375

Warning: Overwriting file C:\Users\brad\Documents\work\random\beast_bug\ex.trees

java.lang.RuntimeException: Negative branch length: -0.1985531009935375

	at beast.evolution.likelihood.BeagleTreeLikelihood.traverse(Unknown Source)

	at beast.evolution.likelihood.BeagleTreeLikelihood.traverse(Unknown Source)

	at beast.evolution.likelihood.BeagleTreeLikelihood.traverse(Unknown Source)

	at beast.evolution.likelihood.BeagleTreeLikelihood.calculateLogP(Unknown Source)

	at beast.evolution.likelihood.TreeLikelihood.calculateLogP(Unknown Source)

	at beast.evolution.likelihood.ThreadedTreeLikelihood.calculateLogPByBeagle(Unknown Source)

	at beast.evolution.likelihood.ThreadedTreeLikelihood.calculateLogP(Unknown Source)

	at beast.core.util.CompoundDistribution.calculateLogP(Unknown Source)

	at beast.core.util.CompoundDistribution.calculateLogP(Unknown Source)

	at beast.core.MCMC.propagateState(Unknown Source)

	at beast.core.MCMC.doLoop(Unknown Source)

	at beast.core.MCMC.run(Unknown Source)

	at beast.app.BeastMCMC.run(Unknown Source)

	at beast.app.beastapp.BeastMain.<init>(Unknown Source)

	at beast.app.beastapp.BeastMain.main(Unknown Source)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:567)

	at beast.app.beastapp.BeastLauncher.run(Unknown Source)

	at beast.app.beastapp.BeastLauncher.main(Unknown Source)

Fatal exception: Negative branch length: -0.1985531009935375
```

I believe that I have found the source of this error. The TipDateRandomWalker allows the sampled tip height to be less the 0. If two sampled tips have the same parent and both of the tips receive a negative height from the walker and then the Uniform operator shifts the height of the shared parent node to also be negative, then when one of these tips is sampled again the  following line may give the tip a positive height and thus the edge between the tip and the parent will be negative.

https://github.com/CompEvol/beast2/blob/46951afef0058a677793a86456bc9b69661471c6/src/beast/evolution/operators/TipDatesRandomWalker.java#L87

Here, the sampled tip date will reflected about 0 since it is less than 0 and become positive.

I don't know how much of an issue it is for BEAST to have negative height nodes/tips, but for my analyses I would like to be able to date tips past the latest sampling point. I have thought of a few ways to fix this:

1. Make `reflectValue` a parameter, since the reflecting is the cause of the problem.
2. Set the `0` in the above line to be the minimum height of the tree.
3. Change the order of the if statement in `TipDateRandomWalker.reflectValue()` so that it will reflect on the parent height before reflecting over 0.

If negative heights are a problem then:

4. Readjust the heights after applying the TipDateRandomWalker so that the minimum height is 0.
5. Ensure that the TipDateRandomWalker cannot set negative heights. This would be a problem for me, since I want to sample dates later than the latest time point.

**Comment by brj1** [comment]
The Scaler operator may also scale a node with a negative height past the

**Comment by rbouckaert** [comment]
The issue with adding dummy tips afterwards is that there is no absolute time information in the tree file, so it won't be possible to know for sure at which height to set the dummy node wrt the remainder of the tree. However, it is possible to write a tree logger that adds such dummy node and thus not influences the posterior. Perhaps that in combination with allowing negative node heights will do the trick.

**Comment by brj1** [comment]
For my analyses, not all of my tips get adjusted so I know what time / height certain tips are at. Specifically I know which tips should be height 0.

However, your idea would work better overall, though one issue is that the youngest possible date would have to be known a priori. I might add that logger into the package I am making since it would fit in nicely if that is okay with you.

**Comment by rbouckaert** [comment]
Sure, feel free to create any logger that is useful for you in your package. I think setting the range to reflect in to (min(0,node height) , parent height) instead of (0, parent height) will fix the original issue you reported.
